import type { Locale } from "./i18n";

// B1 전표 정본. 두 화면이 함께 쓰며 @features 안에서만 가져온다.
export const M = {
  ko: {
    entry: "이 스팟으로 연습", busy: "연습 문제를 저장하는 중…", tab: "내 스팟", presetTab: "프리셋 연습",
    empty: "계산을 마친 결과 화면에서 [이 스팟으로 연습]을 누르면 문제가 여기에 저장됩니다.",
    loading: "내 스팟을 불러오는 중…", storageNote: "이 기기에 최근 20개 스팟과 스팟별 최근 500개 기록을 저장합니다. 내 스팟 기록은 별도로 집계합니다. 같은 스팟을 다시 저장하면 이전 풀이를 바꾸고 연습 기록을 초기화합니다.",
    source: "직접 계산한 근사 풀이 · 목표 오차 {target}% · 달성 {achieved}%", lockAssumption: "전략 일부 고정 가정",
    chooseSpot: "저장된 스팟", deleteSpot: "스팟 삭제", deleteConfirm: "이 스팟과 연습 기록을 이 기기에서 삭제할까요?",
    loadError: "저장된 스팟을 불러오지 못했습니다. 다시 열어 주세요.", saveError: "저장하지 못했습니다. 다시 시도해 주세요.",
    captureError: "이 결과에서 연습 문제를 만들지 못했습니다. 풀이가 완료됐는지 확인해 주세요.",
    noQuestion: "이 스팟에서 출제할 수 있는 핸드가 없습니다.", board: "보드", hand: "내 핸드", pot: "팟", stack: "스택", line: "진행",
    prompt: "어떤 액션을 선택하시겠습니까?", next: "다음 문제", review: "틀린 문제 복습", practice: "일반 연습", attemptCount: "이 스팟 풀이 {count}회",
    verdictBest: "최적 선택", verdictGood: "허용 가능한 선택", verdictBad: "다시 볼 스팟", evLoss: "EV 손실", frequency: "빈도", actionEv: "액션 EV", chips: "칩",
  },
  en: {
    entry: "Practice this spot", busy: "Saving practice questions…", tab: "My spots", presetTab: "Preset practice",
    empty: "After solving a spot, choose [Practice this spot] on the results screen to save questions here.",
    loading: "Loading your spots…", storageNote: "This device stores your 20 most recent spots and 500 latest attempts per spot. My spot results are counted separately. Saving the same spot again replaces its solve and clears its practice history.",
    source: "Your approximate solve · Target error {target}% · Achieved {achieved}%", lockAssumption: "Assumes part of the strategy is fixed",
    chooseSpot: "Saved spots", deleteSpot: "Delete spot", deleteConfirm: "Delete this spot and its practice history from this device?",
    loadError: "Could not load your saved spots. Please reopen this screen.", saveError: "Could not save. Please try again.",
    captureError: "Could not create practice questions from these results. Check that the solve has finished.",
    noQuestion: "There are no playable hands in this spot.", board: "Board", hand: "Your hand", pot: "Pot", stack: "Stack", line: "Line",
    prompt: "What's your play?", next: "Next question", review: "Review mistakes", practice: "Regular practice", attemptCount: "Attempts in this spot: {count}",
    verdictBest: "Best play", verdictGood: "Acceptable", verdictBad: "Review this spot", evLoss: "EV loss", frequency: "Frequency", actionEv: "Action EV", chips: "chips",
  },
  ja: {
    entry: "このスポットで練習", busy: "練習問題を保存中…", tab: "自分のスポット", presetTab: "プリセット練習",
    empty: "計算後、結果画面の[このスポットで練習]から問題を保存できます。",
    loading: "スポットを読込中…", storageNote: "この端末に最新20スポット、各500回分の記録を保存します。成績は別集計です。同じスポットを再保存すると計算結果が置き換わり、練習記録が消えます。",
    source: "自分で計算した近似解 · 目標誤差 {target}% · 到達 {achieved}%", lockAssumption: "戦略の一部を固定した仮定",
    chooseSpot: "保存したスポット", deleteSpot: "スポットを削除", deleteConfirm: "この端末からスポットと練習記録を削除しますか？",
    loadError: "保存したスポットを読み込めませんでした。画面を開き直してください。", saveError: "保存できませんでした。再試行してください。",
    captureError: "練習問題を作れませんでした。計算の完了を確認してください。",
    noQuestion: "出題できるハンドがありません。", board: "ボード", hand: "自分のハンド", pot: "ポット", stack: "スタック", line: "ライン",
    prompt: "どのアクションを選びますか？", next: "次の問題", review: "間違いを復習", practice: "通常練習", attemptCount: "このスポットの練習 {count}回",
    verdictBest: "最適な選択", verdictGood: "許容できる選択", verdictBad: "要復習", evLoss: "EVロス", frequency: "頻度", actionEv: "アクションEV", chips: "チップ",
  },
  es: {
    entry: "Practicar este spot", busy: "Guardando preguntas…", tab: "Mis spots", presetTab: "Practicar ejemplos",
    empty: "Tras resolver un spot, pulsa [Practicar este spot] en los resultados para guardar preguntas aquí.",
    loading: "Cargando tus spots…", storageNote: "Este dispositivo guarda tus 20 spots más recientes y los últimos 500 intentos de cada uno. Tus resultados se cuentan por separado. Guardar de nuevo el mismo spot sustituye su cálculo y borra su historial de práctica.",
    source: "Tu cálculo aproximado · Error objetivo {target}% · Alcanzado {achieved}%", lockAssumption: "Supone parte de la estrategia fijada",
    chooseSpot: "Spots guardados", deleteSpot: "Borrar spot", deleteConfirm: "¿Borrar este spot y su historial de práctica de este dispositivo?",
    loadError: "No se pudieron cargar tus spots. Vuelve a abrir esta pantalla.", saveError: "No se pudo guardar. Inténtalo de nuevo.",
    captureError: "No se pudieron crear preguntas con estos resultados. Comprueba que el cálculo haya terminado.",
    noQuestion: "No hay manos disponibles para practicar en este spot.", board: "Board", hand: "Tu mano", pot: "Bote", stack: "Stack", line: "Línea",
    prompt: "¿Cuál es tu jugada?", next: "Siguiente pregunta", review: "Repasar errores", practice: "Práctica normal", attemptCount: "Intentos en este spot: {count}",
    verdictBest: "Mejor jugada", verdictGood: "Aceptable", verdictBad: "Repasa este spot", evLoss: "Pérdida de EV", frequency: "Frecuencia", actionEv: "EV de la acción", chips: "fichas",
  },
  pt: {
    entry: "Praticar este spot", busy: "Salvando questões…", tab: "Meus spots", presetTab: "Praticar exemplos",
    empty: "Depois de calcular um spot, toque em [Praticar este spot] nos resultados para salvar questões aqui.",
    loading: "Carregando seus spots…", storageNote: "Este dispositivo guarda seus 20 spots mais recentes e as últimas 500 tentativas de cada um. Seus resultados são contabilizados separadamente. Salvar o mesmo spot novamente substitui o cálculo e apaga o histórico de prática.",
    source: "Seu cálculo aproximado · Erro alvo {target}% · Atingido {achieved}%", lockAssumption: "Pressupõe parte da estratégia fixada",
    chooseSpot: "Spots salvos", deleteSpot: "Excluir spot", deleteConfirm: "Excluir este spot e seu histórico de prática deste dispositivo?",
    loadError: "Não foi possível carregar seus spots. Abra esta tela novamente.", saveError: "Não foi possível salvar. Tente novamente.",
    captureError: "Não foi possível criar questões com esses resultados. Confira se o cálculo terminou.",
    noQuestion: "Não há mãos disponíveis para praticar neste spot.", board: "Board", hand: "Sua mão", pot: "Pote", stack: "Stack", line: "Linha",
    prompt: "Qual é a sua jogada?", next: "Próxima questão", review: "Revisar erros", practice: "Prática normal", attemptCount: "Tentativas neste spot: {count}",
    verdictBest: "Melhor jogada", verdictGood: "Aceitável", verdictBad: "Revise este spot", evLoss: "Perda de EV", frequency: "Frequência", actionEv: "EV da ação", chips: "fichas",
  },
  de: {
    entry: "Diesen Spot üben", busy: "Übungsfragen werden gespeichert…", tab: "Meine Spots", presetTab: "Beispiele üben",
    empty: "Wähle nach deiner Berechnung im Ergebnis [Diesen Spot üben], um hier Fragen zu speichern.",
    loading: "Deine Spots werden geladen…", storageNote: "Dieses Gerät speichert deine 20 neuesten Spots und die letzten 500 Versuche je Spot. Deine Ergebnisse werden getrennt gezählt. Erneutes Speichern desselben Spots ersetzt die Berechnung und löscht den Übungsverlauf.",
    source: "Deine Näherungsrechnung · Zielfehler {target}% · Erreicht {achieved}%", lockAssumption: "Annahme einer teilweise fixierten Strategie",
    chooseSpot: "Gespeicherte Spots", deleteSpot: "Spot löschen", deleteConfirm: "Diesen Spot und seinen Übungsverlauf von diesem Gerät löschen?",
    loadError: "Deine Spots konnten nicht geladen werden. Öffne diese Ansicht erneut.", saveError: "Speichern fehlgeschlagen. Versuche es erneut.",
    captureError: "Aus diesem Ergebnis konnten keine Übungsfragen erstellt werden. Prüfe, ob die Berechnung abgeschlossen ist.",
    noQuestion: "In diesem Spot gibt es keine spielbaren Hände.", board: "Board", hand: "Deine Hand", pot: "Pot", stack: "Stack", line: "Line",
    prompt: "Was spielst du?", next: "Nächste Frage", review: "Fehler wiederholen", practice: "Normal üben", attemptCount: "Versuche in diesem Spot: {count}",
    verdictBest: "Beste Wahl", verdictGood: "Vertretbar", verdictBad: "Nochmal ansehen", evLoss: "EV-Verlust", frequency: "Häufigkeit", actionEv: "Aktions-EV", chips: "Chips",
  },
  zh: {
    entry: "用这个场景练习", busy: "正在保存练习题…", tab: "我的场景", presetTab: "预设练习",
    empty: "完成计算后，在结果页面点击[用这个场景练习]，即可将题目保存在这里。",
    loading: "正在加载你的场景…", storageNote: "本设备保存最近20个场景及每个场景最近500条记录。我的场景成绩单独统计。重新保存同一场景会替换计算结果并清除练习记录。",
    source: "自行计算的近似解 · 目标误差 {target}% · 已达 {achieved}%", lockAssumption: "假设部分策略固定",
    chooseSpot: "已保存的场景", deleteSpot: "删除场景", deleteConfirm: "要从本设备删除这个场景及其练习记录吗？",
    loadError: "无法加载已保存的场景。请重新打开此页面。", saveError: "保存失败，请重试。",
    captureError: "无法从这些结果生成练习题。请确认计算已经完成。",
    noQuestion: "此场景没有可用于练习的手牌。", board: "公共牌", hand: "我的手牌", pot: "底池", stack: "筹码量", line: "线路",
    prompt: "你打算怎么打？", next: "下一题", review: "复习错题", practice: "普通练习", attemptCount: "此场景已练习 {count}次",
    verdictBest: "最优选择", verdictGood: "可以接受的选择", verdictBad: "该回头复盘", evLoss: "EV 损失", frequency: "频率", actionEv: "行动EV", chips: "筹码",
  },
  "zh-hant": {
    entry: "用這個場景練習", busy: "正在儲存練習題…", tab: "我的場景", presetTab: "預設練習",
    empty: "完成計算後，在結果頁面點選[用這個場景練習]，即可將題目儲存在這裡。",
    loading: "正在載入你的場景…", storageNote: "此裝置儲存最近20個場景及每個場景最近500筆紀錄。我的場景成績分開統計。重新儲存同一場景會取代計算結果並清除練習紀錄。",
    source: "自行計算的近似解 · 目標誤差 {target}% · 已達 {achieved}%", lockAssumption: "假設部分策略固定",
    chooseSpot: "已儲存的場景", deleteSpot: "刪除場景", deleteConfirm: "要從此裝置刪除這個場景及其練習紀錄嗎？",
    loadError: "無法載入已儲存的場景。請重新開啟此頁面。", saveError: "儲存失敗，請重試。",
    captureError: "無法從這些結果建立練習題。請確認計算已經完成。",
    noQuestion: "此場景沒有可用於練習的手牌。", board: "公共牌", hand: "我的手牌", pot: "底池", stack: "籌碼量", line: "線路",
    prompt: "你打算怎麼打？", next: "下一題", review: "複習錯題", practice: "一般練習", attemptCount: "此場景已練習 {count}次",
    verdictBest: "最佳選擇", verdictGood: "可以接受的選擇", verdictBad: "該回頭檢討", evLoss: "EV 損失", frequency: "頻率", actionEv: "行動EV", chips: "籌碼",
  },
  fr: {
    entry: "Travailler ce spot", busy: "Enregistrement des exercices…", tab: "Mes spots", presetTab: "Travailler les exemples",
    empty: "Après ton calcul, choisis [Travailler ce spot] dans les résultats pour enregistrer des exercices ici.",
    loading: "Chargement de tes spots…", storageNote: "Cet appareil conserve tes 20 spots les plus récents et les 500 derniers essais par spot. Tes résultats sont comptés séparément. Enregistrer à nouveau le même spot remplace son calcul et efface son historique d’entraînement.",
    source: "Ton calcul approché · Erreur cible {target} % · Atteinte {achieved} %", lockAssumption: "Hypothèse d’une stratégie partiellement fixée",
    chooseSpot: "Spots enregistrés", deleteSpot: "Supprimer le spot", deleteConfirm: "Supprimer ce spot et son historique d’entraînement de cet appareil ?",
    loadError: "Impossible de charger tes spots. Rouvre cet écran.", saveError: "Enregistrement impossible. Réessaie.",
    captureError: "Impossible de créer des exercices à partir de ces résultats. Vérifie que le calcul est terminé.",
    noQuestion: "Aucune main jouable dans ce spot.", board: "Board", hand: "Ta main", pot: "Pot", stack: "Stack", line: "Ligne",
    prompt: "Tu joues quoi ?", next: "Question suivante", review: "Revoir les erreurs", practice: "Entraînement normal", attemptCount: "Essais sur ce spot : {count}",
    verdictBest: "Meilleur choix", verdictGood: "Acceptable", verdictBad: "Spot à revoir", evLoss: "Perte d’EV", frequency: "Fréquence", actionEv: "EV de l’action", chips: "jetons",
  },
  id: {
    entry: "Latih spot ini", busy: "Menyimpan soal latihan…", tab: "Spot saya", presetTab: "Latihan preset",
    empty: "Setelah menghitung spot, pilih [Latih spot ini] pada hasil untuk menyimpan soal di sini.",
    loading: "Memuat spot Anda…", storageNote: "Perangkat ini menyimpan 20 spot terbaru dan 500 percobaan terakhir per spot. Hasil spot Anda dihitung terpisah. Menyimpan ulang spot yang sama mengganti hasil perhitungan dan menghapus riwayat latihannya.",
    source: "Hasil perhitungan pendekatan Anda · Target galat {target}% · Tercapai {achieved}%", lockAssumption: "Mengasumsikan sebagian strategi dikunci",
    chooseSpot: "Spot tersimpan", deleteSpot: "Hapus spot", deleteConfirm: "Hapus spot ini dan riwayat latihannya dari perangkat ini?",
    loadError: "Spot tersimpan gagal dimuat. Buka kembali halaman ini.", saveError: "Gagal menyimpan. Silakan coba lagi.",
    captureError: "Soal latihan gagal dibuat dari hasil ini. Pastikan perhitungannya sudah selesai.",
    noQuestion: "Tidak ada hand yang dapat dilatih dalam spot ini.", board: "Board", hand: "Hand Anda", pot: "Pot", stack: "Stack", line: "Line",
    prompt: "Apa keputusan Anda?", next: "Soal berikutnya", review: "Tinjau kesalahan", practice: "Latihan biasa", attemptCount: "Percobaan pada spot ini: {count}",
    verdictBest: "Pilihan terbaik", verdictGood: "Cukup baik", verdictBad: "Perlu ditinjau", evLoss: "Kerugian EV", frequency: "Frekuensi", actionEv: "EV aksi", chips: "chip",
  },
  ms: {
    entry: "Berlatih spot ini", busy: "Menyimpan soalan latihan…", tab: "Spot saya", presetTab: "Latihan pratetap",
    empty: "Selepas pengiraan spot selesai, pilih [Berlatih spot ini] pada keputusan untuk menyimpan soalan di sini.",
    loading: "Memuatkan spot anda…", storageNote: "Peranti ini menyimpan 20 spot terkini dan 500 cubaan terkini bagi setiap spot. Keputusan spot anda dikira berasingan. Menyimpan semula spot yang sama menggantikan pengiraan dan memadamkan rekod latihannya.",
    source: "Pengiraan anggaran anda · Ralat sasaran {target}% · Dicapai {achieved}%", lockAssumption: "Andaian sebahagian strategi dikunci",
    chooseSpot: "Spot tersimpan", deleteSpot: "Padam spot", deleteConfirm: "Padam spot ini dan rekod latihannya daripada peranti ini?",
    loadError: "Spot tersimpan tidak dapat dimuatkan. Buka semula skrin ini.", saveError: "Tidak dapat menyimpan. Sila cuba lagi.",
    captureError: "Soalan latihan tidak dapat dihasilkan daripada keputusan ini. Pastikan pengiraan telah selesai.",
    noQuestion: "Tiada tangan yang boleh dilatih dalam spot ini.", board: "Board", hand: "Tangan anda", pot: "Pot", stack: "Stack", line: "Line",
    prompt: "Apa keputusan anda?", next: "Soalan seterusnya", review: "Ulang kaji kesilapan", practice: "Latihan biasa", attemptCount: "Cubaan untuk spot ini: {count}",
    verdictBest: "Pilihan terbaik", verdictGood: "Boleh diterima", verdictBad: "Perlu disemak", evLoss: "Kerugian EV", frequency: "Kekerapan", actionEv: "EV tindakan", chips: "cip",
  },
  hi: {
    entry: "इस स्पॉट का अभ्यास करें", busy: "अभ्यास के सवाल सहेजे जा रहे हैं…", tab: "मेरे स्पॉट", presetTab: "प्रीसेट अभ्यास",
    empty: "स्पॉट की गणना पूरी होने पर, परिणाम में [इस स्पॉट का अभ्यास करें] चुनें। सवाल यहाँ सहेजे जाएँगे।",
    loading: "आपके स्पॉट लोड हो रहे हैं…", storageNote: "इस डिवाइस पर आपके सबसे हाल के 20 स्पॉट और हर स्पॉट के पिछले 500 प्रयास सहेजे जाते हैं। आपके परिणाम अलग गिने जाते हैं। उसी स्पॉट को फिर सहेजने से पुरानी गणना बदल जाती है और अभ्यास का इतिहास मिट जाता है।",
    source: "आपकी अनुमानित गणना · लक्ष्य त्रुटि {target}% · प्राप्त {achieved}%", lockAssumption: "रणनीति का एक हिस्सा लॉक होने की धारणा",
    chooseSpot: "सहेजे गए स्पॉट", deleteSpot: "स्पॉट मिटाएँ", deleteConfirm: "इस डिवाइस से यह स्पॉट और इसके अभ्यास का इतिहास मिटाएँ?",
    loadError: "सहेजे गए स्पॉट लोड नहीं हो सके। यह स्क्रीन फिर से खोलें।", saveError: "सहेजा नहीं जा सका। फिर से कोशिश करें।",
    captureError: "इन परिणामों से अभ्यास के सवाल नहीं बन सके। जाँचें कि गणना पूरी हो गई है।",
    noQuestion: "इस स्पॉट में अभ्यास के लिए कोई हैंड उपलब्ध नहीं है।", board: "बोर्ड", hand: "आपका हैंड", pot: "पॉट", stack: "स्टैक", line: "एक्शन क्रम",
    prompt: "आप क्या करेंगे?", next: "अगला सवाल", review: "गलतियों का अभ्यास", practice: "सामान्य अभ्यास", attemptCount: "इस स्पॉट में प्रयास: {count}",
    verdictBest: "सर्वोत्तम", verdictGood: "स्वीकार्य", verdictBad: "नुकसान वाला चुनाव", evLoss: "EV नुकसान", frequency: "आवृत्ति", actionEv: "एक्शन EV", chips: "चिप्स",
  },
} satisfies Record<Locale, Record<string, string>>;

export type CustomTrainerLabelKey = keyof typeof M.ko;
