import type { Locale } from "./i18n";

// R2 문구 전표 정본. 복기 기능 진입점 안에서만 가져온다.
// 숫자 자리표시자를 바꾼 뒤 화면에서는 기존 localizeNumber()를 적용한다.
export const M = {
  ko: {
    title: "핸드 복기", situation: "상황", hero: "내 자리", opener: "오픈한 자리", preflop: "프리플랍",
    singleRaised: "오픈 · 콜", threeBet: "3벳 팟", multiway: "3인 이상", comingSoon: "준비 중",
    unavailableScenario: "이 상황의 자료는 아직 준비 중입니다.", fileMissing: "이 플랍의 결과 파일이 없습니다.",
    loadFailed: "결과 파일을 불러오지 못했습니다.", invalidData: "결과 파일을 읽을 수 없습니다.",
    unsupportedAction: "이 액션은 분석할 수 없습니다.", unsupportedSize: "이 크기는 분석할 수 없습니다.",
    evMissing: "EV 없음", referenceOnly: "참고만", mixedAction: "솔버가 쓰는 선택",
    precomputed: "미리 계산한 결과", onDevice: "이 기기에서 계산", flop: "플랍", turn: "턴", river: "리버",
    chooseHand: "내 카드 2장", chooseFlop: "플랍 3장", chooseTurn: "턴 카드", chooseRiver: "리버 카드",
    actions: "액션 고르기", history: "판 기록", result: "결과", totalLoss: "손실 합계", mistakes: "실수",
    best: "최적 선택", good: "허용 가능한 선택", mistake: "다시 볼 선택",
    noResults: "내 카드를 고르고 액션을 누르면 결과가 나옵니다.", chooseAction: "실제로 한 액션을 고르세요.",
    opponentResponse: "내 선택 뒤 상대 반응", folds: "접음", calls: "받음", raises: "레이즈", foldingHands: "접는 핸드",
    handGrid: "핸드 표", frequency: "빈도", loss: "손실", matchedSize: "크기 맞춤 {actual} → {used}",
    undo: "되돌리기", newHand: "새 판", loading: "자료 불러오는 중…", solving: "계산 중…",
    solveFailed: "이 거리의 계산을 마치지 못했습니다.", retry: "다시 시도", complete: "이 판 종료", nextStreet: "다음 카드",
    check: "체크", fold: "폴드", call: "콜", bet: "벳", raise: "레이즈", allin: "올인",
    scopeNote: "온라인 캐시 6맥스 100bb 기준 · 무료. 펍·토너먼트에는 맞지 않을 수 있습니다. 3인 이상·3벳 팟은 준비 중입니다.",
    referenceNote: "양쪽 도달 비중의 곱이 {threshold} 미만인 자리는 실수 개수와 손실 합계에서 뺍니다.",
    evMissingNote: "손실을 판단할 EV가 없습니다. 빈도만 표시합니다.", reach: "도달 비중의 곱", accuracy: "목표 오차",
    pot: "팟", heroOutsideRange: "이 핸드는 선택한 자리의 기본 레인지 밖입니다.",
    board: "보드", stack: "남은 스택", otherSizes: "다른 크기", size: "크기", heroTurn: "내 차례", opponentTurn: "상대 차례",
    noOpponentResponse: "이 선택 뒤에 상대 액션이 없습니다.", noFoldingHands: "이 선택 뒤에 접는 핸드가 없습니다.",
    selectHistory: "내 행동을 누르면 그 자리의 결과를 봅니다.", notReviewed: "분석 못 함", hand: "내 핸드",
    free: "무료", open: "오픈", opponent: "상대", selectedAction: "내 선택", noMistake: "실수 아님",
    navTitle: "핸드 복기", cancel: "취소", handOutsideRange: "기본 레인지 밖의 핸드", analysedDecisions: "분석한 선택",
    noCompatibleHands: "이 보드에서 가능한 핸드가 없습니다.", otherSize: "다른 크기", actualSize: "실제 크기", usedSize: "분석에 쓴 크기",
    rangeSource: "프리플랍 차트의 레인지", unanalysed: "분석 못 함", chooseRank: "숫자 고르기", chooseSuit: "무늬 고르기", scopeTitle: "계산 기준",
  },
  en: {
    title: "Hand review", situation: "Situation", hero: "Your seat", opener: "Opening seat", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-bet pot", multiway: "3+ players", comingSoon: "In preparation",
    unavailableScenario: "Data for this situation is not ready yet.", fileMissing: "No result file is available for this flop.",
    loadFailed: "Could not load the result file.", invalidData: "Could not read the result file.",
    unsupportedAction: "This action cannot be analysed.", unsupportedSize: "This size cannot be analysed.",
    evMissing: "EV unavailable", referenceOnly: "Reference only", mixedAction: "Used by the solver",
    precomputed: "Precomputed result", onDevice: "Calculated on this device", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Your 2 cards", chooseFlop: "3 flop cards", chooseTurn: "Turn card", chooseRiver: "River card",
    actions: "Choose an action", history: "Hand history", result: "Results", totalLoss: "Total loss", mistakes: "Mistakes",
    best: "Best play", good: "Acceptable", mistake: "Review this play",
    noResults: "Choose your cards and enter actions to see results.", chooseAction: "Choose the action that was played.",
    opponentResponse: "Opponent response to your play", folds: "Folds", calls: "Calls", raises: "Raises", foldingHands: "Hands that fold",
    handGrid: "Hand grid", frequency: "Frequency", loss: "Loss", matchedSize: "Size matched {actual} → {used}",
    undo: "Undo", newHand: "New hand", loading: "Loading data…", solving: "Calculating…",
    solveFailed: "Could not finish calculating this street.", retry: "Retry", complete: "Hand complete", nextStreet: "Next card",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Free · Online 6-max cash, 100bb. Results may not suit pub games or tournaments. Multiway and 3-bet pots are in preparation.",
    referenceNote: "Spots with a reach-share product below {threshold} are excluded from mistake counts and total loss.",
    evMissingNote: "EV is unavailable for judging loss. Only frequencies are shown.", reach: "Reach-share product", accuracy: "Target error",
    pot: "Pot", heroOutsideRange: "This hand is outside the default range for the selected seat.",
    board: "Board", stack: "Remaining stack", otherSizes: "Other sizes", size: "Size", heroTurn: "Your turn", opponentTurn: "Opponent's turn",
    noOpponentResponse: "No opponent action follows this play.", noFoldingHands: "No hands fold after this play.",
    selectHistory: "Select one of your actions to see that spot's results.", notReviewed: "Not analysed", hand: "Your hand",
    free: "Free", open: "Open", opponent: "Opponent", selectedAction: "Your play", noMistake: "Not a mistake",
    navTitle: "Hand review", cancel: "Cancel", handOutsideRange: "Hand outside default range", analysedDecisions: "Analysed decisions",
    noCompatibleHands: "No hands are compatible with this board.", otherSize: "Other size", actualSize: "Actual size", usedSize: "Size used for analysis",
    rangeSource: "Ranges from preflop charts", unanalysed: "Not analysed", chooseRank: "Choose rank", chooseSuit: "Choose suit", scopeTitle: "Review assumptions",
  },
  ja: {
    title: "ハンド振り返り", situation: "状況", hero: "自分の席", opener: "オープンした席", preflop: "プリフロップ",
    singleRaised: "オープン・コール", threeBet: "3ベットポット", multiway: "3人以上", comingSoon: "準備中",
    unavailableScenario: "この状況のデータはまだ準備中です。", fileMissing: "このフロップの結果ファイルがありません。",
    loadFailed: "結果ファイルを取得できませんでした。", invalidData: "結果ファイルを読み取れませんでした。",
    unsupportedAction: "このアクションは分析できません。", unsupportedSize: "このサイズは分析できません。",
    evMissing: "EVなし", referenceOnly: "参考のみ", mixedAction: "ソルバーも使う選択",
    precomputed: "事前計算した結果", onDevice: "この端末で計算", flop: "フロップ", turn: "ターン", river: "リバー",
    chooseHand: "自分のカード2枚", chooseFlop: "フロップ3枚", chooseTurn: "ターンのカード", chooseRiver: "リバーのカード",
    actions: "アクション選択", history: "ハンド履歴", result: "結果", totalLoss: "合計ロス", mistakes: "ミス",
    best: "最適な選択", good: "許容できる選択", mistake: "見直す選択",
    noResults: "カードを選び、実際のアクションを入力すると結果が出ます。", chooseAction: "実際に行ったアクションを選んでください。",
    opponentResponse: "自分の選択への相手の反応", folds: "フォールド", calls: "コール", raises: "レイズ", foldingHands: "フォールドするハンド",
    handGrid: "ハンド表", frequency: "頻度", loss: "ロス", matchedSize: "サイズ補正 {actual} → {used}",
    undo: "元に戻す", newHand: "新しいハンド", loading: "データ取得中…", solving: "計算中…",
    solveFailed: "このストリートの計算を完了できませんでした。", retry: "再試行", complete: "ハンド終了", nextStreet: "次のカード",
    check: "チェック", fold: "フォールド", call: "コール", bet: "ベット", raise: "レイズ", allin: "オールイン",
    scopeNote: "オンラインキャッシュ6人卓・100bb基準、無料。パブでのゲームやトーナメントには合わない場合があります。3人以上・3ベットポットは準備中です。",
    referenceNote: "双方の到達比率の積が{threshold}未満の局面は、ミス数と合計ロスに含めません。",
    evMissingNote: "ロスの判定に必要なEVがありません。頻度のみ表示します。", reach: "到達比率の積", accuracy: "目標誤差",
    pot: "ポット", heroOutsideRange: "このハンドは選んだ席の基本レンジ外です。",
    board: "ボード", stack: "残りスタック", otherSizes: "他のサイズ", size: "サイズ", heroTurn: "自分の番", opponentTurn: "相手の番",
    noOpponentResponse: "この選択の後に相手のアクションはありません。", noFoldingHands: "この選択の後にフォールドするハンドはありません。",
    selectHistory: "自分のアクションを押すと、その局面の結果を表示します。", notReviewed: "分析不可", hand: "自分のハンド",
    free: "無料", open: "オープン", opponent: "相手", selectedAction: "自分の選択", noMistake: "ミスではない",
    navTitle: "ハンド振り返り", cancel: "キャンセル", handOutsideRange: "基本レンジ外のハンド", analysedDecisions: "分析した選択",
    noCompatibleHands: "このボードで使えるハンドがありません。", otherSize: "別のサイズ", actualSize: "実際のサイズ", usedSize: "分析に使ったサイズ",
    rangeSource: "プリフロップ表のレンジ", unanalysed: "分析不可", chooseRank: "ランクを選択", chooseSuit: "スートを選択", scopeTitle: "計算の前提",
  },
  es: {
    title: "Revisar mano", situation: "Situación", hero: "Tu posición", opener: "Posición que abre", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "Bote 3-bet", multiway: "3+ jugadores", comingSoon: "En preparación",
    unavailableScenario: "Los datos de esta situación aún no están listos.", fileMissing: "No hay archivo de resultados para este flop.",
    loadFailed: "No se pudo cargar el archivo de resultados.", invalidData: "No se pudo leer el archivo de resultados.",
    unsupportedAction: "Esta acción no se puede analizar.", unsupportedSize: "Este tamaño no se puede analizar.",
    evMissing: "EV no disponible", referenceOnly: "Solo referencia", mixedAction: "El solver también la usa",
    precomputed: "Resultado precalculado", onDevice: "Cálculo en este dispositivo", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Tus 2 cartas", chooseFlop: "3 cartas del flop", chooseTurn: "Carta del turn", chooseRiver: "Carta del river",
    actions: "Elegir acción", history: "Historial de la mano", result: "Resultados", totalLoss: "Pérdida total", mistakes: "Errores",
    best: "Mejor jugada", good: "Aceptable", mistake: "Revisar jugada",
    noResults: "Elige tus cartas e introduce las acciones para ver los resultados.", chooseAction: "Elige la acción que se jugó.",
    opponentResponse: "Respuesta rival a tu jugada", folds: "Folds", calls: "Calls", raises: "Raises", foldingHands: "Manos que foldean",
    handGrid: "Tabla de manos", frequency: "Frecuencia", loss: "Pérdida", matchedSize: "Tamaño ajustado {actual} → {used}",
    undo: "Deshacer", newHand: "Nueva mano", loading: "Cargando datos…", solving: "Calculando…",
    solveFailed: "No se pudo completar el cálculo de esta calle.", retry: "Reintentar", complete: "Mano terminada", nextStreet: "Siguiente carta",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Gratis · Cash online de 6 jugadores, 100bb. Puede no ser adecuado para partidas de bar o torneos. Los botes multiway y 3-bet están en preparación.",
    referenceNote: "Los spots cuyo producto de proporciones de llegada sea inferior al {threshold} no cuentan en los errores ni en la pérdida total.",
    evMissingNote: "No hay EV para evaluar la pérdida. Solo se muestran frecuencias.", reach: "Producto de proporciones de llegada", accuracy: "Error objetivo",
    pot: "Bote", heroOutsideRange: "Esta mano no está en el rango base de la posición elegida.",
    board: "Board", stack: "Stack restante", otherSizes: "Otros tamaños", size: "Tamaño", heroTurn: "Tu turno", opponentTurn: "Turno rival",
    noOpponentResponse: "No hay acción rival después de esta jugada.", noFoldingHands: "Ninguna mano foldea después de esta jugada.",
    selectHistory: "Pulsa una de tus acciones para ver los resultados de ese spot.", notReviewed: "Sin analizar", hand: "Tu mano",
    free: "Gratis", open: "Open", opponent: "Rival", selectedAction: "Tu jugada", noMistake: "No es un error",
    navTitle: "Revisar mano", cancel: "Cancelar", handOutsideRange: "Mano fuera del rango base", analysedDecisions: "Decisiones analizadas",
    noCompatibleHands: "No hay manos compatibles con este board.", otherSize: "Otro tamaño", actualSize: "Tamaño real", usedSize: "Tamaño analizado",
    rangeSource: "Rangos de las tablas preflop", unanalysed: "Sin analizar", chooseRank: "Elegir valor", chooseSuit: "Elegir palo", scopeTitle: "Supuestos del análisis",
  },
  pt: {
    title: "Revisar mão", situation: "Situação", hero: "Sua posição", opener: "Posição que abre", preflop: "Pré-flop",
    singleRaised: "Open · Call", threeBet: "Pote 3-bet", multiway: "3+ jogadores", comingSoon: "Em preparação",
    unavailableScenario: "Os dados desta situação ainda não estão prontos.", fileMissing: "Não há arquivo de resultados para este flop.",
    loadFailed: "Não foi possível carregar o arquivo de resultados.", invalidData: "Não foi possível ler o arquivo de resultados.",
    unsupportedAction: "Esta ação não pode ser analisada.", unsupportedSize: "Este tamanho não pode ser analisado.",
    evMissing: "EV indisponível", referenceOnly: "Só referência", mixedAction: "O solver também usa",
    precomputed: "Resultado pré-calculado", onDevice: "Cálculo neste dispositivo", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Suas 2 cartas", chooseFlop: "3 cartas do flop", chooseTurn: "Carta do turn", chooseRiver: "Carta do river",
    actions: "Escolher ação", history: "Histórico da mão", result: "Resultados", totalLoss: "Perda total", mistakes: "Erros",
    best: "Melhor jogada", good: "Aceitável", mistake: "Revisar jogada",
    noResults: "Escolha suas cartas e insira as ações para ver os resultados.", chooseAction: "Escolha a ação que foi jogada.",
    opponentResponse: "Resposta rival à sua jogada", folds: "Folds", calls: "Calls", raises: "Raises", foldingHands: "Mãos que dão fold",
    handGrid: "Tabela de mãos", frequency: "Frequência", loss: "Perda", matchedSize: "Tamanho ajustado {actual} → {used}",
    undo: "Desfazer", newHand: "Nova mão", loading: "Carregando dados…", solving: "Calculando…",
    solveFailed: "Não foi possível concluir o cálculo desta street.", retry: "Tentar de novo", complete: "Mão encerrada", nextStreet: "Próxima carta",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Grátis · Cash online 6-max, 100bb. Pode não servir para jogos de bar ou torneios. Potes multiway e 3-bet estão em preparação.",
    referenceNote: "Spots com produto das proporções de chegada abaixo de {threshold} não entram na contagem de erros nem na perda total.",
    evMissingNote: "Não há EV para avaliar a perda. Apenas frequências são exibidas.", reach: "Produto das proporções de chegada", accuracy: "Erro alvo",
    pot: "Pote", heroOutsideRange: "Esta mão está fora do range base da posição escolhida.",
    board: "Board", stack: "Stack restante", otherSizes: "Outros tamanhos", size: "Tamanho", heroTurn: "Sua vez", opponentTurn: "Vez do rival",
    noOpponentResponse: "Não há ação do rival após esta jogada.", noFoldingHands: "Nenhuma mão dá fold após esta jogada.",
    selectHistory: "Toque em uma das suas ações para ver os resultados daquele spot.", notReviewed: "Sem análise", hand: "Sua mão",
    free: "Grátis", open: "Open", opponent: "Rival", selectedAction: "Sua jogada", noMistake: "Não é erro",
    navTitle: "Revisar mão", cancel: "Cancelar", handOutsideRange: "Mão fora do range base", analysedDecisions: "Decisões analisadas",
    noCompatibleHands: "Não há mãos compatíveis com este board.", otherSize: "Outro tamanho", actualSize: "Tamanho real", usedSize: "Tamanho analisado",
    rangeSource: "Ranges das tabelas pré-flop", unanalysed: "Sem análise", chooseRank: "Escolher valor", chooseSuit: "Escolher naipe", scopeTitle: "Premissas da análise",
  },
  de: {
    title: "Handanalyse", situation: "Situation", hero: "Deine Position", opener: "Eröffnende Position", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-Bet-Pot", multiway: "3+ Spieler", comingSoon: "In Vorbereitung",
    unavailableScenario: "Die Daten für diese Situation sind noch nicht bereit.", fileMissing: "Für diesen Flop gibt es keine Ergebnisdatei.",
    loadFailed: "Die Ergebnisdatei konnte nicht geladen werden.", invalidData: "Die Ergebnisdatei konnte nicht gelesen werden.",
    unsupportedAction: "Diese Aktion kann nicht analysiert werden.", unsupportedSize: "Diese Größe kann nicht analysiert werden.",
    evMissing: "EV fehlt", referenceOnly: "Nur zur Orientierung", mixedAction: "Vom Solver gespielt",
    precomputed: "Vorberechnetes Ergebnis", onDevice: "Auf diesem Gerät berechnet", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Deine 2 Karten", chooseFlop: "3 Flopkarten", chooseTurn: "Turnkarte", chooseRiver: "Riverkarte",
    actions: "Aktion wählen", history: "Handverlauf", result: "Ergebnis", totalLoss: "Gesamtverlust", mistakes: "Fehler",
    best: "Beste Wahl", good: "Vertretbar", mistake: "Spielzug prüfen",
    noResults: "Wähle deine Karten und die gespielten Aktionen, um Ergebnisse zu sehen.", chooseAction: "Wähle die tatsächlich gespielte Aktion.",
    opponentResponse: "Reaktion auf deinen Spielzug", folds: "Folds", calls: "Calls", raises: "Raises", foldingHands: "Hände, die folden",
    handGrid: "Handtabelle", frequency: "Häufigkeit", loss: "Verlust", matchedSize: "Größe angepasst {actual} → {used}",
    undo: "Zurück", newHand: "Neue Hand", loading: "Daten werden geladen…", solving: "Berechnung läuft…",
    solveFailed: "Die Berechnung dieser Setzrunde konnte nicht abgeschlossen werden.", retry: "Erneut versuchen", complete: "Hand beendet", nextStreet: "Nächste Karte",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Kostenlos · Online-Cash, 6-max, 100bb. Für Pubspiele oder Turniere möglicherweise ungeeignet. Multiway- und 3-Bet-Pots sind in Vorbereitung.",
    referenceNote: "Spots mit einem Produkt der Erreichungsanteile unter {threshold} zählen weder als Fehler noch zum Gesamtverlust.",
    evMissingNote: "Ohne EV lässt sich der Verlust nicht bewerten. Es werden nur Häufigkeiten angezeigt.", reach: "Produkt der Erreichungsanteile", accuracy: "Zielfehler",
    pot: "Pot", heroOutsideRange: "Diese Hand liegt außerhalb der Standardrange der gewählten Position.",
    board: "Board", stack: "Restlicher Stack", otherSizes: "Andere Größen", size: "Größe", heroTurn: "Du bist dran", opponentTurn: "Gegner ist dran",
    noOpponentResponse: "Auf diesen Spielzug folgt keine gegnerische Aktion.", noFoldingHands: "Nach diesem Spielzug foldet keine Hand.",
    selectHistory: "Wähle eine deiner Aktionen, um das Ergebnis dieses Spots zu sehen.", notReviewed: "Nicht analysiert", hand: "Deine Hand",
    free: "Kostenlos", open: "Open", opponent: "Gegner", selectedAction: "Dein Spielzug", noMistake: "Kein Fehler",
    navTitle: "Handanalyse", cancel: "Abbrechen", handOutsideRange: "Hand außerhalb der Standardrange", analysedDecisions: "Analysierte Entscheidungen",
    noCompatibleHands: "Keine Hand passt zu diesem Board.", otherSize: "Andere Größe", actualSize: "Tatsächliche Größe", usedSize: "Analysierte Größe",
    rangeSource: "Ranges aus Preflop-Tabellen", unanalysed: "Nicht analysiert", chooseRank: "Rang wählen", chooseSuit: "Farbe wählen", scopeTitle: "Annahmen der Analyse",
  },
  zh: {
    title: "手牌复盘", situation: "场景", hero: "我的位置", opener: "开池位置", preflop: "翻牌前",
    singleRaised: "开池 · 跟注", threeBet: "3-bet底池", multiway: "3人及以上", comingSoon: "准备中",
    unavailableScenario: "此场景的数据尚未准备好。", fileMissing: "没有此翻牌的结果文件。",
    loadFailed: "无法加载结果文件。", invalidData: "无法读取结果文件。",
    unsupportedAction: "无法分析此行动。", unsupportedSize: "无法分析此下注尺度。",
    evMissing: "无EV数据", referenceOnly: "仅供参考", mixedAction: "求解器也会采用",
    precomputed: "预先计算的结果", onDevice: "在本设备计算", flop: "翻牌", turn: "转牌", river: "河牌",
    chooseHand: "我的2张底牌", chooseFlop: "3张翻牌", chooseTurn: "转牌", chooseRiver: "河牌",
    actions: "选择行动", history: "手牌记录", result: "结果", totalLoss: "损失合计", mistakes: "失误",
    best: "最优选择", good: "可以接受", mistake: "需要复盘",
    noResults: "选好底牌并点选实际行动后，即可查看结果。", chooseAction: "请选择实际采取的行动。",
    opponentResponse: "我行动后对手的反应", folds: "弃牌", calls: "跟注", raises: "加注", foldingHands: "弃牌的手牌",
    handGrid: "手牌表", frequency: "频率", loss: "损失", matchedSize: "尺度匹配 {actual} → {used}",
    undo: "撤销", newHand: "新一手", loading: "正在加载数据…", solving: "正在计算…",
    solveFailed: "未能完成此轮的计算。", retry: "重试", complete: "本手结束", nextStreet: "下一张牌",
    check: "过牌", fold: "弃牌", call: "跟注", bet: "下注", raise: "加注", allin: "全下",
    scopeNote: "免费 · 以线上6人桌现金局、100bb为准。结果可能不适合酒吧牌局或锦标赛。3人及以上、3-bet底池准备中。",
    referenceNote: "双方到达比重的乘积低于{threshold}的场景，不计入失误次数和损失合计。",
    evMissingNote: "没有用于判断损失的EV数据，仅显示频率。", reach: "到达比重的乘积", accuracy: "目标误差",
    pot: "底池", heroOutsideRange: "此手牌不在所选位置的默认范围内。",
    board: "公共牌", stack: "剩余筹码", otherSizes: "其他尺度", size: "尺度", heroTurn: "轮到我", opponentTurn: "轮到对手",
    noOpponentResponse: "此行动后没有对手行动。", noFoldingHands: "此行动后没有弃牌的手牌。",
    selectHistory: "点击自己的行动，查看该场景的结果。", notReviewed: "无法分析", hand: "我的手牌",
    free: "免费", open: "开池", opponent: "对手", selectedAction: "我的选择", noMistake: "不算失误",
    navTitle: "手牌复盘", cancel: "取消", handOutsideRange: "默认范围外的手牌", analysedDecisions: "已分析的决策",
    noCompatibleHands: "此公共牌下没有可用的手牌。", otherSize: "其他尺度", actualSize: "实际尺度", usedSize: "分析使用的尺度",
    rangeSource: "范围来自翻牌前图表", unanalysed: "无法分析", chooseRank: "选择点数", chooseSuit: "选择花色", scopeTitle: "计算前提",
  },
  "zh-hant": {
    title: "手牌檢討", situation: "情境", hero: "我的位置", opener: "開池位置", preflop: "翻牌前",
    singleRaised: "開池 · 跟注", threeBet: "3-bet底池", multiway: "3人以上", comingSoon: "準備中",
    unavailableScenario: "此情境的資料尚未準備好。", fileMissing: "沒有此翻牌的結果檔案。",
    loadFailed: "無法載入結果檔案。", invalidData: "無法讀取結果檔案。",
    unsupportedAction: "無法分析此行動。", unsupportedSize: "無法分析此下注尺度。",
    evMissing: "無EV資料", referenceOnly: "僅供參考", mixedAction: "解算器也會採用",
    precomputed: "預先計算的結果", onDevice: "在此裝置計算", flop: "翻牌", turn: "轉牌", river: "河牌",
    chooseHand: "我的2張底牌", chooseFlop: "3張翻牌", chooseTurn: "轉牌", chooseRiver: "河牌",
    actions: "選擇行動", history: "手牌紀錄", result: "結果", totalLoss: "損失合計", mistakes: "失誤",
    best: "最佳選擇", good: "可以接受", mistake: "需要檢討",
    noResults: "選好底牌並點選實際行動後，即可查看結果。", chooseAction: "請選擇實際採取的行動。",
    opponentResponse: "我行動後對手的反應", folds: "蓋牌", calls: "跟注", raises: "加注", foldingHands: "會蓋掉的手牌",
    handGrid: "手牌表", frequency: "頻率", loss: "損失", matchedSize: "尺度對應 {actual} → {used}",
    undo: "復原", newHand: "新一手", loading: "正在載入資料…", solving: "正在計算…",
    solveFailed: "未能完成此輪的計算。", retry: "重試", complete: "此手結束", nextStreet: "下一張牌",
    check: "過牌", fold: "蓋牌", call: "跟注", bet: "下注", raise: "加注", allin: "全下",
    scopeNote: "免費 · 以線上6人桌現金局、100bb為準。結果可能不適合酒吧牌局或錦標賽。3人以上、3-bet底池準備中。",
    referenceNote: "雙方到達比重的乘積低於{threshold}的情境，不計入失誤次數和損失合計。",
    evMissingNote: "沒有用來判斷損失的EV資料，僅顯示頻率。", reach: "到達比重的乘積", accuracy: "目標誤差",
    pot: "底池", heroOutsideRange: "此手牌不在所選位置的預設範圍內。",
    board: "公共牌", stack: "剩餘籌碼", otherSizes: "其他尺度", size: "尺度", heroTurn: "輪到我", opponentTurn: "輪到對手",
    noOpponentResponse: "此行動後沒有對手行動。", noFoldingHands: "此行動後沒有會蓋掉的手牌。",
    selectHistory: "點選自己的行動，查看該情境的結果。", notReviewed: "無法分析", hand: "我的手牌",
    free: "免費", open: "開池", opponent: "對手", selectedAction: "我的選擇", noMistake: "不算失誤",
    navTitle: "手牌檢討", cancel: "取消", handOutsideRange: "預設範圍外的手牌", analysedDecisions: "已分析的決策",
    noCompatibleHands: "此公共牌下沒有可用的手牌。", otherSize: "其他尺度", actualSize: "實際尺度", usedSize: "分析使用的尺度",
    rangeSource: "範圍來自翻牌前圖表", unanalysed: "無法分析", chooseRank: "選擇點數", chooseSuit: "選擇花色", scopeTitle: "計算前提",
  },
  fr: {
    title: "Revoir une main", situation: "Situation", hero: "Ta position", opener: "Position d’ouverture", preflop: "Préflop",
    singleRaised: "Open · Call", threeBet: "Pot 3-bet", multiway: "3 joueurs ou plus", comingSoon: "En préparation",
    unavailableScenario: "Les données de cette situation ne sont pas encore prêtes.", fileMissing: "Aucun fichier de résultats pour ce flop.",
    loadFailed: "Impossible de charger le fichier de résultats.", invalidData: "Impossible de lire le fichier de résultats.",
    unsupportedAction: "Cette action ne peut pas être analysée.", unsupportedSize: "Ce sizing ne peut pas être analysé.",
    evMissing: "EV indisponible", referenceOnly: "À titre indicatif", mixedAction: "Joué par le solveur",
    precomputed: "Résultat précalculé", onDevice: "Calcul sur cet appareil", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Tes 2 cartes", chooseFlop: "3 cartes du flop", chooseTurn: "Carte du turn", chooseRiver: "Carte de la river",
    actions: "Choisir une action", history: "Historique de la main", result: "Résultats", totalLoss: "Perte totale", mistakes: "Erreurs",
    best: "Meilleur choix", good: "Acceptable", mistake: "Action à revoir",
    noResults: "Choisis tes cartes et les actions jouées pour voir les résultats.", chooseAction: "Choisis l’action réellement jouée.",
    opponentResponse: "Réaction adverse à ton choix", folds: "Folds", calls: "Calls", raises: "Relances", foldingHands: "Mains qui foldent",
    handGrid: "Grille de mains", frequency: "Fréquence", loss: "Perte", matchedSize: "Sizing ajusté {actual} → {used}",
    undo: "Annuler", newHand: "Nouvelle main", loading: "Chargement des données…", solving: "Calcul en cours…",
    solveFailed: "Le calcul de cette street n’a pas pu aboutir.", retry: "Réessayer", complete: "Main terminée", nextStreet: "Carte suivante",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Gratuit · Cash en ligne à 6 joueurs, 100bb. Peut ne pas convenir aux parties de bar ou aux tournois. Les pots multiway et 3-bet sont en préparation.",
    referenceNote: "Les spots dont le produit des proportions d’arrivée est inférieur à {threshold} sont exclus du nombre d’erreurs et de la perte totale.",
    evMissingNote: "EV indisponible pour évaluer la perte. Seules les fréquences sont affichées.", reach: "Produit des proportions d’arrivée", accuracy: "Erreur cible",
    pot: "Pot", heroOutsideRange: "Cette main est hors de la range par défaut de la position choisie.",
    board: "Board", stack: "Stack restant", otherSizes: "Autres sizings", size: "Sizing", heroTurn: "À toi", opponentTurn: "À l’adversaire",
    noOpponentResponse: "Aucune action adverse ne suit ce choix.", noFoldingHands: "Aucune main ne folde après ce choix.",
    selectHistory: "Choisis une de tes actions pour voir les résultats de ce spot.", notReviewed: "Non analysé", hand: "Ta main",
    free: "Gratuit", open: "Open", opponent: "Adversaire", selectedAction: "Ton choix", noMistake: "Pas une erreur",
    navTitle: "Revoir une main", cancel: "Annuler", handOutsideRange: "Main hors de la range par défaut", analysedDecisions: "Décisions analysées",
    noCompatibleHands: "Aucune main compatible avec ce board.", otherSize: "Autre sizing", actualSize: "Sizing réel", usedSize: "Sizing analysé",
    rangeSource: "Ranges des tableaux préflop", unanalysed: "Non analysé", chooseRank: "Choisir la valeur", chooseSuit: "Choisir la couleur", scopeTitle: "Hypothèses de l’analyse",
  },
  id: {
    title: "Tinjau hand", situation: "Situasi", hero: "Posisi Anda", opener: "Posisi pembuka", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "Pot 3-bet", multiway: "3+ pemain", comingSoon: "Sedang disiapkan",
    unavailableScenario: "Data untuk situasi ini belum tersedia.", fileMissing: "Tidak ada berkas hasil untuk flop ini.",
    loadFailed: "Berkas hasil tidak dapat dimuat.", invalidData: "Berkas hasil tidak dapat dibaca.",
    unsupportedAction: "Aksi ini tidak dapat dianalisis.", unsupportedSize: "Ukuran ini tidak dapat dianalisis.",
    evMissing: "EV tidak tersedia", referenceOnly: "Hanya referensi", mixedAction: "Juga dipakai solver",
    precomputed: "Hasil perhitungan sebelumnya", onDevice: "Dihitung di perangkat ini", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "2 kartu Anda", chooseFlop: "3 kartu flop", chooseTurn: "Kartu turn", chooseRiver: "Kartu river",
    actions: "Pilih aksi", history: "Riwayat hand", result: "Hasil", totalLoss: "Total kerugian", mistakes: "Kesalahan",
    best: "Pilihan terbaik", good: "Dapat diterima", mistake: "Perlu ditinjau",
    noResults: "Pilih kartu Anda dan masukkan aksi untuk melihat hasil.", chooseAction: "Pilih aksi yang benar-benar dimainkan.",
    opponentResponse: "Respons lawan setelah aksi Anda", folds: "Fold", calls: "Call", raises: "Raise", foldingHands: "Hand yang fold",
    handGrid: "Tabel hand", frequency: "Frekuensi", loss: "Kerugian", matchedSize: "Ukuran disesuaikan {actual} → {used}",
    undo: "Urungkan", newHand: "Hand baru", loading: "Memuat data…", solving: "Menghitung…",
    solveFailed: "Perhitungan street ini tidak dapat diselesaikan.", retry: "Coba lagi", complete: "Hand selesai", nextStreet: "Kartu berikutnya",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Gratis · Cash online 6-max, 100bb. Hasil mungkin tidak cocok untuk permainan di bar atau turnamen. Pot multiway dan 3-bet sedang disiapkan.",
    referenceNote: "Spot dengan hasil kali proporsi jangkauan di bawah {threshold} tidak dihitung dalam jumlah kesalahan dan total kerugian.",
    evMissingNote: "EV untuk menilai kerugian tidak tersedia. Hanya frekuensi yang ditampilkan.", reach: "Hasil kali proporsi jangkauan", accuracy: "Target galat",
    pot: "Pot", heroOutsideRange: "Hand ini berada di luar range awal posisi yang dipilih.",
    board: "Board", stack: "Sisa stack", otherSizes: "Ukuran lain", size: "Ukuran", heroTurn: "Giliran Anda", opponentTurn: "Giliran lawan",
    noOpponentResponse: "Tidak ada aksi lawan setelah pilihan ini.", noFoldingHands: "Tidak ada hand yang fold setelah pilihan ini.",
    selectHistory: "Ketuk salah satu aksi Anda untuk melihat hasil spot tersebut.", notReviewed: "Tidak dianalisis", hand: "Hand Anda",
    free: "Gratis", open: "Open", opponent: "Lawan", selectedAction: "Pilihan Anda", noMistake: "Bukan kesalahan",
    navTitle: "Tinjau hand", cancel: "Batal", handOutsideRange: "Hand di luar range awal", analysedDecisions: "Keputusan dianalisis",
    noCompatibleHands: "Tidak ada hand yang sesuai dengan board ini.", otherSize: "Ukuran lain", actualSize: "Ukuran sebenarnya", usedSize: "Ukuran yang dianalisis",
    rangeSource: "Range dari tabel preflop", unanalysed: "Tidak dianalisis", chooseRank: "Pilih nilai", chooseSuit: "Pilih lambang", scopeTitle: "Asumsi analisis",
  },
  ms: {
    title: "Semak hand", situation: "Keadaan", hero: "Kedudukan anda", opener: "Kedudukan pembuka", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "Pot 3-bet", multiway: "3 pemain ke atas", comingSoon: "Dalam persediaan",
    unavailableScenario: "Data bagi keadaan ini belum siap.", fileMissing: "Tiada fail keputusan untuk flop ini.",
    loadFailed: "Fail keputusan gagal dimuatkan.", invalidData: "Fail keputusan tidak dapat dibaca.",
    unsupportedAction: "Tindakan ini tidak dapat dianalisis.", unsupportedSize: "Saiz ini tidak dapat dianalisis.",
    evMissing: "EV tiada", referenceOnly: "Rujukan sahaja", mixedAction: "Digunakan oleh solver",
    precomputed: "Keputusan yang dikira awal", onDevice: "Dikira pada peranti ini", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "2 kad anda", chooseFlop: "3 kad flop", chooseTurn: "Kad turn", chooseRiver: "Kad river",
    actions: "Pilih tindakan", history: "Sejarah hand", result: "Keputusan", totalLoss: "Jumlah kerugian", mistakes: "Kesilapan",
    best: "Pilihan terbaik", good: "Boleh diterima", mistake: "Perlu disemak",
    noResults: "Pilih kad anda dan tindakan yang dimainkan untuk melihat keputusan.", chooseAction: "Pilih tindakan yang dimainkan ketika itu.",
    opponentResponse: "Tindak balas lawan terhadap anda", folds: "Fold", calls: "Call", raises: "Raise", foldingHands: "Hand yang fold",
    handGrid: "Jadual hand", frequency: "Kekerapan", loss: "Kerugian", matchedSize: "Saiz dipadankan {actual} → {used}",
    undo: "Buat asal", newHand: "Hand baharu", loading: "Memuatkan data…", solving: "Pengiraan berjalan…",
    solveFailed: "Pengiraan untuk street ini tidak dapat disiapkan.", retry: "Cuba semula", complete: "Hand tamat", nextStreet: "Kad seterusnya",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Percuma · Cash dalam talian 6-max, 100bb. Mungkin tidak sesuai untuk permainan di pub atau kejohanan. Pot multiway dan 3-bet masih dalam persediaan.",
    referenceNote: "Spot dengan hasil darab bahagian capaian di bawah {threshold} dikecualikan daripada bilangan kesilapan dan jumlah kerugian.",
    evMissingNote: "Tiada EV untuk menilai kerugian. Hanya kekerapan dipaparkan.", reach: "Hasil darab bahagian capaian", accuracy: "Ralat sasaran",
    pot: "Pot", heroOutsideRange: "Hand ini di luar range lalai bagi kedudukan yang dipilih.",
    board: "Board", stack: "Baki stack", otherSizes: "Saiz lain", size: "Saiz", heroTurn: "Giliran anda", opponentTurn: "Giliran lawan",
    noOpponentResponse: "Tiada tindakan lawan selepas pilihan ini.", noFoldingHands: "Tiada hand yang fold selepas pilihan ini.",
    selectHistory: "Tekan tindakan anda untuk melihat keputusan spot berkenaan.", notReviewed: "Belum dianalisis", hand: "Hand anda",
    free: "Percuma", open: "Open", opponent: "Lawan", selectedAction: "Pilihan anda", noMistake: "Bukan kesilapan",
    navTitle: "Semak hand", cancel: "Batal", handOutsideRange: "Hand di luar range lalai", analysedDecisions: "Keputusan dianalisis",
    noCompatibleHands: "Tiada hand yang serasi dengan board ini.", otherSize: "Saiz lain", actualSize: "Saiz sebenar", usedSize: "Saiz untuk analisis",
    rangeSource: "Range daripada carta preflop", unanalysed: "Belum dianalisis", chooseRank: "Pilih nilai kad", chooseSuit: "Pilih bunga kad", scopeTitle: "Andaian semakan",
  },
  hi: {
    title: "हैंड की समीक्षा", situation: "स्थिति", hero: "आपकी पोज़िशन", opener: "Open करने की पोज़िशन", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-bet pot", multiway: "3 या अधिक खिलाड़ी", comingSoon: "तैयारी जारी है",
    unavailableScenario: "इस स्थिति का डेटा अभी तैयार नहीं है।", fileMissing: "इस Flop की नतीजा फ़ाइल उपलब्ध नहीं है।",
    loadFailed: "नतीजा फ़ाइल लोड नहीं हो सकी।", invalidData: "नतीजा फ़ाइल पढ़ी नहीं जा सकी।",
    unsupportedAction: "इस ऐक्शन का विश्लेषण नहीं हो सकता।", unsupportedSize: "इस साइज़ का विश्लेषण नहीं हो सकता।",
    evMissing: "EV उपलब्ध नहीं", referenceOnly: "केवल संदर्भ", mixedAction: "Solver भी यह चुनता है",
    precomputed: "पहले से गणना किया गया नतीजा", onDevice: "इस डिवाइस पर गणना", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "आपके 2 कार्ड", chooseFlop: "Flop के 3 कार्ड", chooseTurn: "Turn कार्ड", chooseRiver: "River कार्ड",
    actions: "ऐक्शन चुनें", history: "हैंड का रिकॉर्ड", result: "नतीजे", totalLoss: "कुल नुकसान", mistakes: "गलतियाँ",
    best: "सबसे अच्छा विकल्प", good: "स्वीकार्य", mistake: "इस चाल को दोबारा देखें",
    noResults: "नतीजे देखने के लिए अपने कार्ड और खेले गए ऐक्शन चुनें।", chooseAction: "वह ऐक्शन चुनें जो वास्तव में खेला गया था।",
    opponentResponse: "आपकी चाल पर विरोधी की प्रतिक्रिया", folds: "Fold", calls: "Call", raises: "Raise", foldingHands: "Fold करने वाले हैंड",
    handGrid: "हैंड की तालिका", frequency: "फ़्रीक्वेंसी", loss: "नुकसान", matchedSize: "साइज़ मिलाया गया {actual} → {used}",
    undo: "पिछला कदम", newHand: "नया हैंड", loading: "डेटा लोड हो रहा है…", solving: "गणना जारी है…",
    solveFailed: "इस Street की गणना पूरी नहीं हो सकी।", retry: "फिर कोशिश करें", complete: "हैंड पूरा हुआ", nextStreet: "अगला कार्ड",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "मुफ़्त · ऑनलाइन 6-max Cash, 100bb के लिए। पब गेम या टूर्नामेंट में नतीजे उपयुक्त नहीं भी हो सकते हैं। Multiway और 3-bet pot की तैयारी जारी है।",
    referenceNote: "दोनों खिलाड़ियों के पहुँच अनुपात का गुणनफल {threshold} से कम हो तो वह स्थिति गलतियों की गिनती और कुल नुकसान में शामिल नहीं होती।",
    evMissingNote: "नुकसान जाँचने के लिए EV उपलब्ध नहीं है। केवल फ़्रीक्वेंसी दिखाई गई है।", reach: "पहुँच अनुपातों का गुणनफल", accuracy: "लक्षित त्रुटि",
    pot: "Pot", heroOutsideRange: "यह हैंड चुनी गई पोज़िशन की डिफ़ॉल्ट Range में नहीं है।",
    board: "Board", stack: "बचा हुआ Stack", otherSizes: "अन्य साइज़", size: "साइज़", heroTurn: "आपकी बारी", opponentTurn: "विरोधी की बारी",
    noOpponentResponse: "इस चाल के बाद विरोधी का कोई ऐक्शन नहीं है।", noFoldingHands: "इस चाल के बाद कोई हैंड Fold नहीं करता।",
    selectHistory: "उस स्थिति का नतीजा देखने के लिए अपना कोई ऐक्शन दबाएँ।", notReviewed: "विश्लेषण नहीं हुआ", hand: "आपका हैंड",
    free: "मुफ़्त", open: "Open", opponent: "विरोधी", selectedAction: "आपकी चाल", noMistake: "गलती नहीं",
    navTitle: "हैंड समीक्षा", cancel: "रद्द करें", handOutsideRange: "डिफ़ॉल्ट Range से बाहर का हैंड", analysedDecisions: "विश्लेषित फैसले",
    noCompatibleHands: "इस Board के साथ कोई हैंड संभव नहीं है।", otherSize: "अन्य साइज़", actualSize: "असली साइज़", usedSize: "विश्लेषण का साइज़",
    rangeSource: "Preflop चार्ट से Range", unanalysed: "विश्लेषण नहीं हुआ", chooseRank: "कार्ड का रैंक चुनें", chooseSuit: "कार्ड का सूट चुनें", scopeTitle: "समीक्षा की मान्यताएँ",
  },
} as const;

export type HandReviewLabelKey = keyof typeof M.en;
export type HandReviewLabels = Record<HandReviewLabelKey, string>;
// This assignment checks both the locale set and every required key at build time.
const checkedLabels: Record<Locale, HandReviewLabels> = M;
export const handReviewLabels = (locale: Locale): HandReviewLabels => checkedLabels[locale];
