import type { Locale, LocaleDict } from "./i18n";

// R2 문구 전표 정본. 복기 기능 진입점 안에서만 가져온다.
// 숫자 자리표시자를 바꾼 뒤 화면에서는 기존 localizeNumber()를 적용한다.
export const M = {
  ko: {
    title: "핸드 복기", situation: "상황", hero: "내 자리", opener: "오픈한 자리", caller: "콜한 자리", threeBettor: "3벳한 자리", preflop: "프리플랍",
    singleRaised: "오픈 · 콜", threeBet: "3벳 팟", multiway: "3인 이상", notSupported: "복기할 수 없음",
    unavailableScenario: "이 상황의 자료는 아직 준비 중입니다.", fileMissing: "이 플랍의 결과 파일이 없습니다.",
    loadFailed: "결과 파일을 불러오지 못했습니다.", invalidData: "결과 파일을 읽을 수 없습니다.",
    unsupportedAction: "이 액션은 분석할 수 없습니다.", unsupportedSize: "이 크기는 분석할 수 없습니다.",
    evMissing: "EV 없음", referenceOnly: "참고만", mixedAction: "솔버가 쓰는 선택",
    precomputed: "미리 계산한 결과", onDevice: "이 기기에서 계산", flop: "플랍", turn: "턴", river: "리버",
    chooseHand: "내 카드 2장", chooseFlop: "플랍 3장", chooseTurn: "턴 카드", chooseRiver: "리버 카드",
    result: "결과", totalLoss: "손실 합계",
    best: "최적 선택", good: "허용 가능한 선택", mistake: "다시 볼 선택",
    noResults: "내 카드를 고르고 액션을 누르면 결과가 나옵니다.", chooseAction: "실제로 한 액션을 고르세요.",
    opponentResponse: "내 선택 뒤 상대 반응", foldingHands: "접는 핸드",
    handGrid: "핸드 표", matchedSize: "크기 맞춤 {actual} → {used}",
    undo: "되돌리기", newHand: "새 판", loading: "자료 불러오는 중…", solving: "계산 중…",
    solveFailed: "이 스트리트의 계산을 마치지 못했습니다.", retry: "다시 시도", complete: "이 판 종료",
    check: "체크", fold: "폴드", call: "콜", bet: "벳", raise: "레이즈", allin: "올인",
    scopeNote: "온라인 캐시 6맥스 100bb 기준 · 무료. 펍·토너먼트에는 맞지 않을 수 있습니다. 3벳 팟은 준비 중이고, 3인 이상 팟은 복기할 수 없습니다.",
    referenceNote: "양쪽 도달 비중의 곱이 {threshold} 미만인 자리는 실수 개수와 손실 합계에서 뺍니다.",
    evMissingNote: "손실을 판단할 EV가 없습니다. 빈도만 표시합니다.", reach: "도달 비중의 곱",
    pot: "팟", heroOutsideRange: "이 핸드는 선택한 자리의 기본 레인지 밖입니다.",
    hand: "내 핸드",
    navTitle: "핸드 복기", cancel: "취소",
    noCompatibleHands: "내 카드와 겹치지 않는 상대 핸드가 이 자리에 없습니다.", otherSize: "다른 크기",
    unanalysed: "분석 못 함", scopeTitle: "계산 기준",
    practiceSpot: "이 자리 연습하기", practiceBusy: "연습 문제를 만드는 중…", practiceUnavailable: "연습 문제를 만들 수 없습니다. 내 레인지에서 이 자리에 오는 핸드가 없거나, 액션별 EV가 없거나, 고를 액션이 하나뿐입니다.", practiceReferenceNote: "도달 비중이 낮아 계산값을 믿기 어려운 자리입니다. 참고로만 보고, 틀린 문제 복습에는 넣지 않습니다.", practiceError: "연습 문제를 저장하지 못했습니다. 다시 시도해 주세요.",
  },
  en: {
    title: "Hand review", situation: "Situation", hero: "Your seat", opener: "Opening seat", caller: "Calling seat", threeBettor: "3-betting seat", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-bet pot", multiway: "3+ players", notSupported: "Cannot be reviewed",
    unavailableScenario: "Data for this situation is not ready yet.", fileMissing: "No result file is available for this flop.",
    loadFailed: "Could not load the result file.", invalidData: "Could not read the result file.",
    unsupportedAction: "This action cannot be analysed.", unsupportedSize: "This size cannot be analysed.",
    evMissing: "EV unavailable", referenceOnly: "Reference only", mixedAction: "Used by the solver",
    precomputed: "Precomputed result", onDevice: "Calculated on this device", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Your 2 cards", chooseFlop: "3 flop cards", chooseTurn: "Turn card", chooseRiver: "River card",
    result: "Results", totalLoss: "Total loss",
    best: "Best play", good: "Acceptable", mistake: "Review this play",
    noResults: "Choose your cards and enter actions to see results.", chooseAction: "Choose the action that was played.",
    opponentResponse: "Opponent response to your play", foldingHands: "Hands that fold",
    handGrid: "Hand grid", matchedSize: "Size matched {actual} → {used}",
    undo: "Undo", newHand: "New hand", loading: "Loading data…", solving: "Calculating…",
    solveFailed: "Could not finish calculating this street.", retry: "Retry", complete: "Hand complete",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Free · Online 6-max cash, 100bb. Results may not suit pub games or tournaments. 3-bet pots are in preparation; multiway pots cannot be reviewed.",
    referenceNote: "Spots with a reach-share product below {threshold} are excluded from mistake counts and total loss.",
    evMissingNote: "EV is unavailable for judging loss. Only frequencies are shown.", reach: "Reach-share product",
    pot: "Pot", heroOutsideRange: "This hand is outside the default range for the selected seat.",
    hand: "Your hand",
    navTitle: "Hand review", cancel: "Cancel",
    noCompatibleHands: "No opponent hand in this spot is compatible with your cards.", otherSize: "Other size",
    unanalysed: "Not analysed", scopeTitle: "Review assumptions",
    practiceSpot: "Practice this spot", practiceBusy: "Creating practice questions…", practiceUnavailable: "Practice questions cannot be created: no hand in your range reaches this spot, action EVs are missing, or there is only one action to choose.", practiceReferenceNote: "This spot is reached too rarely for reliable values. Use it as a reference only; it is not added to your mistake review.", practiceError: "Could not save practice questions. Please try again.",
  },
  ja: {
    title: "ハンド振り返り", situation: "状況", hero: "自分の席", opener: "オープンした席", caller: "コールした席", threeBettor: "3ベットした席", preflop: "プリフロップ",
    singleRaised: "オープン・コール", threeBet: "3ベットポット", multiway: "3人以上", notSupported: "振り返り不可",
    unavailableScenario: "この状況のデータはまだ準備中です。", fileMissing: "このフロップの結果ファイルがありません。",
    loadFailed: "結果ファイルを取得できませんでした。", invalidData: "結果ファイルを読み取れませんでした。",
    unsupportedAction: "このアクションは分析できません。", unsupportedSize: "このサイズは分析できません。",
    evMissing: "EVなし", referenceOnly: "参考のみ", mixedAction: "ソルバーも使う選択",
    precomputed: "事前計算した結果", onDevice: "この端末で計算", flop: "フロップ", turn: "ターン", river: "リバー",
    chooseHand: "自分のカード2枚", chooseFlop: "フロップ3枚", chooseTurn: "ターンのカード", chooseRiver: "リバーのカード",
    result: "結果", totalLoss: "合計ロス",
    best: "最適な選択", good: "許容できる選択", mistake: "見直す選択",
    noResults: "カードを選び、実際のアクションを入力すると結果が出ます。", chooseAction: "実際に行ったアクションを選んでください。",
    opponentResponse: "自分の選択への相手の反応", foldingHands: "フォールドするハンド",
    handGrid: "ハンド表", matchedSize: "サイズ補正 {actual} → {used}",
    undo: "元に戻す", newHand: "新しいハンド", loading: "データ取得中…", solving: "計算中…",
    solveFailed: "このストリートの計算を完了できませんでした。", retry: "再試行", complete: "ハンド終了",
    check: "チェック", fold: "フォールド", call: "コール", bet: "ベット", raise: "レイズ", allin: "オールイン",
    scopeNote: "オンラインキャッシュ6人卓・100bb基準、無料。パブでのゲームやトーナメントには合わない場合があります。3ベットポットは準備中です。3人以上のポットは振り返りできません。",
    referenceNote: "双方の到達比率の積が{threshold}未満の局面は、ミス数と合計ロスに含めません。",
    evMissingNote: "ロスの判定に必要なEVがありません。頻度のみ表示します。", reach: "到達比率の積",
    pot: "ポット", heroOutsideRange: "このハンドは選んだ席の基本レンジ外です。",
    hand: "自分のハンド",
    navTitle: "ハンド振り返り", cancel: "キャンセル",
    noCompatibleHands: "このスポットに、自分のカードと重ならない相手のハンドがありません。", otherSize: "別のサイズ",
    unanalysed: "分析不可", scopeTitle: "計算の前提",
    practiceSpot: "このスポットを練習", practiceBusy: "練習問題を作成中…", practiceUnavailable: "練習問題を作れません。自分のレンジでこのスポットに来るハンドがないか、アクションごとのEVがないか、選べるアクションが1つしかありません。", practiceReferenceNote: "到達比率が低く、計算値の信頼性が低いスポットです。参考としてのみ表示し、間違えた問題の復習には入れません。", practiceError: "練習問題を保存できませんでした。もう一度お試しください。",
  },
  es: {
    title: "Revisar mano", situation: "Situación", hero: "Tu posición", opener: "Posición que abre", caller: "Posición que hace call", threeBettor: "Posición que hace 3-bet", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "Bote 3-bet", multiway: "3+ jugadores", notSupported: "No se puede revisar",
    unavailableScenario: "Los datos de esta situación aún no están listos.", fileMissing: "No hay archivo de resultados para este flop.",
    loadFailed: "No se pudo cargar el archivo de resultados.", invalidData: "No se pudo leer el archivo de resultados.",
    unsupportedAction: "Esta acción no se puede analizar.", unsupportedSize: "Este tamaño no se puede analizar.",
    evMissing: "EV no disponible", referenceOnly: "Solo referencia", mixedAction: "El solver también la usa",
    precomputed: "Resultado precalculado", onDevice: "Cálculo en este dispositivo", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Tus 2 cartas", chooseFlop: "3 cartas del flop", chooseTurn: "Carta del turn", chooseRiver: "Carta del river",
    result: "Resultados", totalLoss: "Pérdida total",
    best: "Mejor jugada", good: "Aceptable", mistake: "Revisar jugada",
    noResults: "Elige tus cartas e introduce las acciones para ver los resultados.", chooseAction: "Elige la acción que se jugó.",
    opponentResponse: "Respuesta rival a tu jugada", foldingHands: "Manos que foldean",
    handGrid: "Tabla de manos", matchedSize: "Tamaño ajustado {actual} → {used}",
    undo: "Deshacer", newHand: "Nueva mano", loading: "Cargando datos…", solving: "Calculando…",
    solveFailed: "No se pudo completar el cálculo de esta calle.", retry: "Reintentar", complete: "Mano terminada",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Gratis · Cash online de 6 jugadores, 100bb. Puede no ser adecuado para partidas de bar o torneos. Los botes 3-bet están en preparación; los botes multiway no se pueden revisar.",
    referenceNote: "Los spots cuyo producto de proporciones de llegada sea inferior al {threshold} no cuentan en los errores ni en la pérdida total.",
    evMissingNote: "No hay EV para evaluar la pérdida. Solo se muestran frecuencias.", reach: "Producto de proporciones de llegada",
    pot: "Bote", heroOutsideRange: "Esta mano no está en el rango base de la posición elegida.",
    hand: "Tu mano",
    navTitle: "Revisar mano", cancel: "Cancelar",
    noCompatibleHands: "En este spot no hay manos rivales compatibles con tus cartas.", otherSize: "Otro tamaño",
    unanalysed: "Sin analizar", scopeTitle: "Supuestos del análisis",
    practiceSpot: "Practicar este spot", practiceBusy: "Creando preguntas…", practiceUnavailable: "No se pueden crear preguntas: ninguna mano de tu rango llega a este spot, faltan los EV por acción o solo hay una acción posible.", practiceReferenceNote: "Este spot se alcanza muy pocas veces y sus valores no son fiables. Úsalo solo como referencia; no se añade al repaso de errores.", practiceError: "No se pudieron guardar las preguntas. Inténtalo de nuevo.",
  },
  pt: {
    title: "Revisar mão", situation: "Situação", hero: "Sua posição", opener: "Posição que abre", caller: "Posição que dá call", threeBettor: "Posição que dá 3-bet", preflop: "Pré-flop",
    singleRaised: "Open · Call", threeBet: "Pote 3-bet", multiway: "3+ jogadores", notSupported: "Não pode ser revisado",
    unavailableScenario: "Os dados desta situação ainda não estão prontos.", fileMissing: "Não há arquivo de resultados para este flop.",
    loadFailed: "Não foi possível carregar o arquivo de resultados.", invalidData: "Não foi possível ler o arquivo de resultados.",
    unsupportedAction: "Esta ação não pode ser analisada.", unsupportedSize: "Este tamanho não pode ser analisado.",
    evMissing: "EV indisponível", referenceOnly: "Só referência", mixedAction: "O solver também usa",
    precomputed: "Resultado pré-calculado", onDevice: "Cálculo neste dispositivo", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Suas 2 cartas", chooseFlop: "3 cartas do flop", chooseTurn: "Carta do turn", chooseRiver: "Carta do river",
    result: "Resultados", totalLoss: "Perda total",
    best: "Melhor jogada", good: "Aceitável", mistake: "Revisar jogada",
    noResults: "Escolha suas cartas e insira as ações para ver os resultados.", chooseAction: "Escolha a ação que foi jogada.",
    opponentResponse: "Resposta rival à sua jogada", foldingHands: "Mãos que dão fold",
    handGrid: "Tabela de mãos", matchedSize: "Tamanho ajustado {actual} → {used}",
    undo: "Desfazer", newHand: "Nova mão", loading: "Carregando dados…", solving: "Calculando…",
    solveFailed: "Não foi possível concluir o cálculo desta street.", retry: "Tentar de novo", complete: "Mão encerrada",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Grátis · Cash online 6-max, 100bb. Pode não servir para jogos de bar ou torneios. Potes 3-bet estão em preparação; potes multiway não podem ser revisados.",
    referenceNote: "Spots com produto das proporções de chegada abaixo de {threshold} não entram na contagem de erros nem na perda total.",
    evMissingNote: "Não há EV para avaliar a perda. Apenas frequências são exibidas.", reach: "Produto das proporções de chegada",
    pot: "Pote", heroOutsideRange: "Esta mão está fora do range base da posição escolhida.",
    hand: "Sua mão",
    navTitle: "Revisar mão", cancel: "Cancelar",
    noCompatibleHands: "Neste spot não há mãos do oponente compatíveis com as suas cartas.", otherSize: "Outro tamanho",
    unanalysed: "Sem análise", scopeTitle: "Premissas da análise",
    practiceSpot: "Praticar este spot", practiceBusy: "Criando questões…", practiceUnavailable: "Não é possível criar questões: nenhuma mão do seu range chega a este spot, faltam os EVs por ação ou há apenas uma ação possível.", practiceReferenceNote: "Este spot é alcançado raramente e seus valores não são confiáveis. Use apenas como referência; ele não entra na revisão de erros.", practiceError: "Não foi possível salvar as questões. Tente novamente.",
  },
  de: {
    title: "Handanalyse", situation: "Situation", hero: "Deine Position", opener: "Eröffnende Position", caller: "Callende Position", threeBettor: "3-bettende Position", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-Bet-Pot", multiway: "3+ Spieler", notSupported: "Nicht analysierbar",
    unavailableScenario: "Die Daten für diese Situation sind noch nicht bereit.", fileMissing: "Für diesen Flop gibt es keine Ergebnisdatei.",
    loadFailed: "Die Ergebnisdatei konnte nicht geladen werden.", invalidData: "Die Ergebnisdatei konnte nicht gelesen werden.",
    unsupportedAction: "Diese Aktion kann nicht analysiert werden.", unsupportedSize: "Diese Größe kann nicht analysiert werden.",
    evMissing: "EV fehlt", referenceOnly: "Nur zur Orientierung", mixedAction: "Vom Solver gespielt",
    precomputed: "Vorberechnetes Ergebnis", onDevice: "Auf diesem Gerät berechnet", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Deine 2 Karten", chooseFlop: "3 Flopkarten", chooseTurn: "Turnkarte", chooseRiver: "Riverkarte",
    result: "Ergebnis", totalLoss: "Gesamtverlust",
    best: "Beste Wahl", good: "Vertretbar", mistake: "Spielzug prüfen",
    noResults: "Wähle deine Karten und die gespielten Aktionen, um Ergebnisse zu sehen.", chooseAction: "Wähle die tatsächlich gespielte Aktion.",
    opponentResponse: "Reaktion auf deinen Spielzug", foldingHands: "Hände, die folden",
    handGrid: "Handtabelle", matchedSize: "Größe angepasst {actual} → {used}",
    undo: "Zurück", newHand: "Neue Hand", loading: "Daten werden geladen…", solving: "Berechnung läuft…",
    solveFailed: "Die Berechnung dieser Setzrunde konnte nicht abgeschlossen werden.", retry: "Erneut versuchen", complete: "Hand beendet",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Kostenlos · Online-Cash, 6-max, 100bb. Für Pubspiele oder Turniere möglicherweise ungeeignet. 3-Bet-Pots sind in Vorbereitung; Multiway-Pots können nicht analysiert werden.",
    referenceNote: "Spots mit einem Produkt der Erreichungsanteile unter {threshold} zählen weder als Fehler noch zum Gesamtverlust.",
    evMissingNote: "Ohne EV lässt sich der Verlust nicht bewerten. Es werden nur Häufigkeiten angezeigt.", reach: "Produkt der Erreichungsanteile",
    pot: "Pot", heroOutsideRange: "Diese Hand liegt außerhalb der Standardrange der gewählten Position.",
    hand: "Deine Hand",
    navTitle: "Handanalyse", cancel: "Abbrechen",
    noCompatibleHands: "In diesem Spot ist keine gegnerische Hand mit deinen Karten kompatibel.", otherSize: "Andere Größe",
    unanalysed: "Nicht analysiert", scopeTitle: "Annahmen der Analyse",
    practiceSpot: "Diesen Spot üben", practiceBusy: "Übungsfragen werden erstellt…", practiceUnavailable: "Es können keine Übungsfragen erstellt werden: Keine Hand deiner Range erreicht diesen Spot, die EVs pro Aktion fehlen oder es gibt nur eine mögliche Aktion.", practiceReferenceNote: "Dieser Spot wird zu selten erreicht, um verlässliche Werte zu haben. Nur zur Orientierung – er kommt nicht in die Fehlerwiederholung.", practiceError: "Übungsfragen konnten nicht gespeichert werden. Bitte versuche es erneut.",
  },
  zh: {
    title: "手牌复盘", situation: "场景", hero: "我的位置", opener: "开池位置", caller: "跟注位置", threeBettor: "3-bet位置", preflop: "翻牌前",
    singleRaised: "开池 · 跟注", threeBet: "3-bet底池", multiway: "3人及以上", notSupported: "无法复盘",
    unavailableScenario: "此场景的数据尚未准备好。", fileMissing: "没有此翻牌的结果文件。",
    loadFailed: "无法加载结果文件。", invalidData: "无法读取结果文件。",
    unsupportedAction: "无法分析此行动。", unsupportedSize: "无法分析此下注尺度。",
    evMissing: "无EV数据", referenceOnly: "仅供参考", mixedAction: "求解器也会采用",
    precomputed: "预先计算的结果", onDevice: "在本设备计算", flop: "翻牌", turn: "转牌", river: "河牌",
    chooseHand: "我的2张底牌", chooseFlop: "3张翻牌", chooseTurn: "转牌", chooseRiver: "河牌",
    result: "结果", totalLoss: "损失合计",
    best: "最优选择", good: "可以接受", mistake: "需要复盘",
    noResults: "选好底牌并点选实际行动后，即可查看结果。", chooseAction: "请选择实际采取的行动。",
    opponentResponse: "我行动后对手的反应", foldingHands: "弃牌的手牌",
    handGrid: "手牌表", matchedSize: "尺度匹配 {actual} → {used}",
    undo: "撤销", newHand: "新一手", loading: "正在加载数据…", solving: "正在计算…",
    solveFailed: "未能完成此轮的计算。", retry: "重试", complete: "本手结束",
    check: "过牌", fold: "弃牌", call: "跟注", bet: "下注", raise: "加注", allin: "全下",
    scopeNote: "免费 · 以线上6人桌现金局、100bb为准。结果可能不适合酒吧牌局或锦标赛。3-bet底池准备中；3人及以上底池无法复盘。",
    referenceNote: "双方到达比重的乘积低于{threshold}的场景，不计入失误次数和损失合计。",
    evMissingNote: "没有用于判断损失的EV数据，仅显示频率。", reach: "到达比重的乘积",
    pot: "底池", heroOutsideRange: "此手牌不在所选位置的默认范围内。",
    hand: "我的手牌",
    navTitle: "手牌复盘", cancel: "取消",
    noCompatibleHands: "此场景中没有与你的手牌不重叠的对手手牌。", otherSize: "其他尺度",
    unanalysed: "无法分析", scopeTitle: "计算前提",
    practiceSpot: "练习这个场景", practiceBusy: "正在生成练习题…", practiceUnavailable: "无法生成练习题：你的范围中没有手牌会到达这个场景，或缺少各行动的EV，或只有一个可选行动。", practiceReferenceNote: "该场景到达比例过低，计算值不够可靠。仅供参考，不会加入错题复习。", practiceError: "无法保存练习题，请重试。",
  },
  "zh-hant": {
    title: "手牌檢討", situation: "情境", hero: "我的位置", opener: "開池位置", caller: "跟注位置", threeBettor: "3-bet位置", preflop: "翻牌前",
    singleRaised: "開池 · 跟注", threeBet: "3-bet底池", multiway: "3人以上", notSupported: "無法檢討",
    unavailableScenario: "此情境的資料尚未準備好。", fileMissing: "沒有此翻牌的結果檔案。",
    loadFailed: "無法載入結果檔案。", invalidData: "無法讀取結果檔案。",
    unsupportedAction: "無法分析此行動。", unsupportedSize: "無法分析此下注尺度。",
    evMissing: "無EV資料", referenceOnly: "僅供參考", mixedAction: "解算器也會採用",
    precomputed: "預先計算的結果", onDevice: "在此裝置計算", flop: "翻牌", turn: "轉牌", river: "河牌",
    chooseHand: "我的2張底牌", chooseFlop: "3張翻牌", chooseTurn: "轉牌", chooseRiver: "河牌",
    result: "結果", totalLoss: "損失合計",
    best: "最佳選擇", good: "可以接受", mistake: "需要檢討",
    noResults: "選好底牌並點選實際行動後，即可查看結果。", chooseAction: "請選擇實際採取的行動。",
    opponentResponse: "我行動後對手的反應", foldingHands: "會蓋掉的手牌",
    handGrid: "手牌表", matchedSize: "尺度對應 {actual} → {used}",
    undo: "復原", newHand: "新一手", loading: "正在載入資料…", solving: "正在計算…",
    solveFailed: "未能完成此輪的計算。", retry: "重試", complete: "此手結束",
    check: "過牌", fold: "蓋牌", call: "跟注", bet: "下注", raise: "加注", allin: "全下",
    scopeNote: "免費 · 以線上6人桌現金局、100bb為準。結果可能不適合酒吧牌局或錦標賽。3-bet底池準備中；3人以上底池無法檢討。",
    referenceNote: "雙方到達比重的乘積低於{threshold}的情境，不計入失誤次數和損失合計。",
    evMissingNote: "沒有用來判斷損失的EV資料，僅顯示頻率。", reach: "到達比重的乘積",
    pot: "底池", heroOutsideRange: "此手牌不在所選位置的預設範圍內。",
    hand: "我的手牌",
    navTitle: "手牌檢討", cancel: "取消",
    noCompatibleHands: "此場景中沒有與你的手牌不重疊的對手手牌。", otherSize: "其他尺度",
    unanalysed: "無法分析", scopeTitle: "計算前提",
    practiceSpot: "練習這個場景", practiceBusy: "正在產生練習題…", practiceUnavailable: "無法產生練習題：你的範圍中沒有手牌會到達這個場景，或缺少各行動的EV，或只有一個可選行動。", practiceReferenceNote: "該場景到達比例過低，計算值不夠可靠。僅供參考，不會加入錯題複習。", practiceError: "無法儲存練習題，請重試。",
  },
  fr: {
    title: "Revoir une main", situation: "Situation", hero: "Ta position", opener: "Position d’ouverture", caller: "Position qui call", threeBettor: "Position qui 3-bet", preflop: "Préflop",
    singleRaised: "Open · Call", threeBet: "Pot 3-bet", multiway: "3 joueurs ou plus", notSupported: "Impossible à revoir",
    unavailableScenario: "Les données de cette situation ne sont pas encore prêtes.", fileMissing: "Aucun fichier de résultats pour ce flop.",
    loadFailed: "Impossible de charger le fichier de résultats.", invalidData: "Impossible de lire le fichier de résultats.",
    unsupportedAction: "Cette action ne peut pas être analysée.", unsupportedSize: "Ce sizing ne peut pas être analysé.",
    evMissing: "EV indisponible", referenceOnly: "À titre indicatif", mixedAction: "Joué par le solveur",
    precomputed: "Résultat précalculé", onDevice: "Calcul sur cet appareil", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "Tes 2 cartes", chooseFlop: "3 cartes du flop", chooseTurn: "Carte du turn", chooseRiver: "Carte de la river",
    result: "Résultats", totalLoss: "Perte totale",
    best: "Meilleur choix", good: "Acceptable", mistake: "Action à revoir",
    noResults: "Choisis tes cartes et les actions jouées pour voir les résultats.", chooseAction: "Choisis l’action réellement jouée.",
    opponentResponse: "Réaction adverse à ton choix", foldingHands: "Mains qui foldent",
    handGrid: "Grille de mains", matchedSize: "Sizing ajusté {actual} → {used}",
    undo: "Annuler", newHand: "Nouvelle main", loading: "Chargement des données…", solving: "Calcul en cours…",
    solveFailed: "Le calcul de cette street n’a pas pu aboutir.", retry: "Réessayer", complete: "Main terminée",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Gratuit · Cash en ligne à 6 joueurs, 100bb. Peut ne pas convenir aux parties de bar ou aux tournois. Les pots 3-bet sont en préparation ; les pots multiway ne peuvent pas être revus.",
    referenceNote: "Les spots dont le produit des proportions d’arrivée est inférieur à {threshold} sont exclus du nombre d’erreurs et de la perte totale.",
    evMissingNote: "EV indisponible pour évaluer la perte. Seules les fréquences sont affichées.", reach: "Produit des proportions d’arrivée",
    pot: "Pot", heroOutsideRange: "Cette main est hors de la range par défaut de la position choisie.",
    hand: "Ta main",
    navTitle: "Revoir une main", cancel: "Annuler",
    noCompatibleHands: "Dans ce spot, aucune main adverse n’est compatible avec tes cartes.", otherSize: "Autre sizing",
    unanalysed: "Non analysé", scopeTitle: "Hypothèses de l’analyse",
    practiceSpot: "Travailler ce spot", practiceBusy: "Création des exercices…", practiceUnavailable: "Impossible de créer des exercices : aucune main de ta range n’arrive à ce spot, les EV par action manquent, ou il n’y a qu’une seule action possible.", practiceReferenceNote: "Ce spot est atteint trop rarement pour des valeurs fiables. À titre indicatif seulement : il n’est pas ajouté à la révision des erreurs.", practiceError: "Impossible d’enregistrer les exercices. Réessaie.",
  },
  id: {
    title: "Tinjau hand", situation: "Situasi", hero: "Posisi Anda", opener: "Posisi pembuka", caller: "Posisi yang call", threeBettor: "Posisi yang 3-bet", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "Pot 3-bet", multiway: "3+ pemain", notSupported: "Tidak dapat ditinjau",
    unavailableScenario: "Data untuk situasi ini belum tersedia.", fileMissing: "Tidak ada berkas hasil untuk flop ini.",
    loadFailed: "Berkas hasil tidak dapat dimuat.", invalidData: "Berkas hasil tidak dapat dibaca.",
    unsupportedAction: "Aksi ini tidak dapat dianalisis.", unsupportedSize: "Ukuran ini tidak dapat dianalisis.",
    evMissing: "EV tidak tersedia", referenceOnly: "Hanya referensi", mixedAction: "Juga dipakai solver",
    precomputed: "Hasil perhitungan sebelumnya", onDevice: "Dihitung di perangkat ini", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "2 kartu Anda", chooseFlop: "3 kartu flop", chooseTurn: "Kartu turn", chooseRiver: "Kartu river",
    result: "Hasil", totalLoss: "Total kerugian",
    best: "Pilihan terbaik", good: "Dapat diterima", mistake: "Perlu ditinjau",
    noResults: "Pilih kartu Anda dan masukkan aksi untuk melihat hasil.", chooseAction: "Pilih aksi yang benar-benar dimainkan.",
    opponentResponse: "Respons lawan setelah aksi Anda", foldingHands: "Hand yang fold",
    handGrid: "Tabel hand", matchedSize: "Ukuran disesuaikan {actual} → {used}",
    undo: "Urungkan", newHand: "Hand baru", loading: "Memuat data…", solving: "Menghitung…",
    solveFailed: "Perhitungan street ini tidak dapat diselesaikan.", retry: "Coba lagi", complete: "Hand selesai",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Gratis · Cash online 6-max, 100bb. Hasil mungkin tidak cocok untuk permainan di bar atau turnamen. Pot 3-bet sedang disiapkan; pot multiway tidak dapat ditinjau.",
    referenceNote: "Spot dengan hasil kali proporsi jangkauan di bawah {threshold} tidak dihitung dalam jumlah kesalahan dan total kerugian.",
    evMissingNote: "EV untuk menilai kerugian tidak tersedia. Hanya frekuensi yang ditampilkan.", reach: "Hasil kali proporsi jangkauan",
    pot: "Pot", heroOutsideRange: "Hand ini berada di luar range awal posisi yang dipilih.",
    hand: "Hand Anda",
    navTitle: "Tinjau hand", cancel: "Batal",
    noCompatibleHands: "Tidak ada hand lawan di spot ini yang kompatibel dengan kartu Anda.", otherSize: "Ukuran lain",
    unanalysed: "Tidak dianalisis", scopeTitle: "Asumsi analisis",
    practiceSpot: "Latih spot ini", practiceBusy: "Membuat soal latihan…", practiceUnavailable: "Soal latihan tidak dapat dibuat: tidak ada hand di range Anda yang mencapai spot ini, EV per aksi tidak tersedia, atau hanya ada satu aksi yang bisa dipilih.", practiceReferenceNote: "Spot ini terlalu jarang dicapai sehingga nilainya kurang andal. Gunakan hanya sebagai referensi; spot ini tidak dimasukkan ke ulasan kesalahan.", practiceError: "Soal latihan tidak dapat disimpan. Coba lagi.",
  },
  ms: {
    title: "Semak hand", situation: "Keadaan", hero: "Kedudukan anda", opener: "Kedudukan pembuka", caller: "Kedudukan yang call", threeBettor: "Kedudukan yang 3-bet", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "Pot 3-bet", multiway: "3 pemain ke atas", notSupported: "Tidak boleh disemak",
    unavailableScenario: "Data bagi keadaan ini belum siap.", fileMissing: "Tiada fail keputusan untuk flop ini.",
    loadFailed: "Fail keputusan gagal dimuatkan.", invalidData: "Fail keputusan tidak dapat dibaca.",
    unsupportedAction: "Tindakan ini tidak dapat dianalisis.", unsupportedSize: "Saiz ini tidak dapat dianalisis.",
    evMissing: "EV tiada", referenceOnly: "Rujukan sahaja", mixedAction: "Digunakan oleh solver",
    precomputed: "Keputusan yang dikira awal", onDevice: "Dikira pada peranti ini", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "2 kad anda", chooseFlop: "3 kad flop", chooseTurn: "Kad turn", chooseRiver: "Kad river",
    result: "Keputusan", totalLoss: "Jumlah kerugian",
    best: "Pilihan terbaik", good: "Boleh diterima", mistake: "Perlu disemak",
    noResults: "Pilih kad anda dan tindakan yang dimainkan untuk melihat keputusan.", chooseAction: "Pilih tindakan yang dimainkan ketika itu.",
    opponentResponse: "Tindak balas lawan terhadap anda", foldingHands: "Hand yang fold",
    handGrid: "Jadual hand", matchedSize: "Saiz dipadankan {actual} → {used}",
    undo: "Buat asal", newHand: "Hand baharu", loading: "Memuatkan data…", solving: "Pengiraan berjalan…",
    solveFailed: "Pengiraan untuk street ini tidak dapat disiapkan.", retry: "Cuba semula", complete: "Hand tamat",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Percuma · Cash dalam talian 6-max, 100bb. Mungkin tidak sesuai untuk permainan di pub atau kejohanan. Pot 3-bet masih dalam persediaan; pot multiway tidak boleh disemak.",
    referenceNote: "Spot dengan hasil darab bahagian capaian di bawah {threshold} dikecualikan daripada bilangan kesilapan dan jumlah kerugian.",
    evMissingNote: "Tiada EV untuk menilai kerugian. Hanya kekerapan dipaparkan.", reach: "Hasil darab bahagian capaian",
    pot: "Pot", heroOutsideRange: "Hand ini di luar range lalai bagi kedudukan yang dipilih.",
    hand: "Hand anda",
    navTitle: "Semak hand", cancel: "Batal",
    noCompatibleHands: "Tiada hand lawan di spot ini yang serasi dengan kad anda.", otherSize: "Saiz lain",
    unanalysed: "Tidak dapat dianalisis", scopeTitle: "Andaian semakan",
    practiceSpot: "Berlatih spot ini", practiceBusy: "Membuat soalan latihan…", practiceUnavailable: "Soalan latihan tidak dapat dibuat: tiada hand dalam range anda yang sampai ke spot ini, EV setiap aksi tiada, atau hanya ada satu aksi untuk dipilih.", practiceReferenceNote: "Spot ini terlalu jarang dicapai sehingga nilainya kurang boleh dipercayai. Gunakan sebagai rujukan sahaja; ia tidak dimasukkan ke ulang kaji kesilapan.", practiceError: "Soalan latihan tidak dapat disimpan. Cuba lagi.",
  },
  hi: {
    title: "हैंड की समीक्षा", situation: "स्थिति", hero: "आपकी पोज़िशन", opener: "Open करने की पोज़िशन", caller: "Call करने की पोज़िशन", threeBettor: "3-bet करने की पोज़िशन", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-bet pot", multiway: "3 या अधिक खिलाड़ी", notSupported: "समीक्षा संभव नहीं",
    unavailableScenario: "इस स्थिति का डेटा अभी तैयार नहीं है।", fileMissing: "इस Flop की नतीजा फ़ाइल उपलब्ध नहीं है।",
    loadFailed: "नतीजा फ़ाइल लोड नहीं हो सकी।", invalidData: "नतीजा फ़ाइल पढ़ी नहीं जा सकी।",
    unsupportedAction: "इस ऐक्शन का विश्लेषण नहीं हो सकता।", unsupportedSize: "इस साइज़ का विश्लेषण नहीं हो सकता।",
    evMissing: "EV उपलब्ध नहीं", referenceOnly: "केवल संदर्भ", mixedAction: "Solver भी यह चुनता है",
    precomputed: "पहले से गणना किया गया नतीजा", onDevice: "इस डिवाइस पर गणना", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "आपके 2 कार्ड", chooseFlop: "Flop के 3 कार्ड", chooseTurn: "Turn कार्ड", chooseRiver: "River कार्ड",
    result: "नतीजे", totalLoss: "कुल नुकसान",
    best: "सबसे अच्छा विकल्प", good: "स्वीकार्य", mistake: "इस चाल को दोबारा देखें",
    noResults: "नतीजे देखने के लिए अपने कार्ड और खेले गए ऐक्शन चुनें।", chooseAction: "वह ऐक्शन चुनें जो वास्तव में खेला गया था।",
    opponentResponse: "आपकी चाल पर विरोधी की प्रतिक्रिया", foldingHands: "Fold करने वाले हैंड",
    handGrid: "हैंड की तालिका", matchedSize: "साइज़ मिलाया गया {actual} → {used}",
    undo: "पिछला कदम", newHand: "नया हैंड", loading: "डेटा लोड हो रहा है…", solving: "गणना जारी है…",
    solveFailed: "इस Street की गणना पूरी नहीं हो सकी।", retry: "फिर कोशिश करें", complete: "हैंड पूरा हुआ",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "मुफ़्त · ऑनलाइन 6-max Cash, 100bb के लिए। पब गेम या टूर्नामेंट में नतीजे उपयुक्त नहीं भी हो सकते हैं। 3-bet pot की तैयारी जारी है; Multiway pot की समीक्षा नहीं की जा सकती।",
    referenceNote: "दोनों खिलाड़ियों के पहुँच अनुपात का गुणनफल {threshold} से कम हो तो वह स्थिति गलतियों की गिनती और कुल नुकसान में शामिल नहीं होती।",
    evMissingNote: "नुकसान जाँचने के लिए EV उपलब्ध नहीं है। केवल फ़्रीक्वेंसी दिखाई गई है।", reach: "पहुँच अनुपातों का गुणनफल",
    pot: "Pot", heroOutsideRange: "यह हैंड चुनी गई पोज़िशन की डिफ़ॉल्ट Range में नहीं है।",
    hand: "आपका हैंड",
    navTitle: "हैंड समीक्षा", cancel: "रद्द करें",
    noCompatibleHands: "इस स्पॉट में विरोधी का कोई भी हैंड आपके कार्ड के साथ संभव नहीं है।", otherSize: "अन्य साइज़",
    unanalysed: "विश्लेषण नहीं हुआ", scopeTitle: "समीक्षा की मान्यताएँ",
    practiceSpot: "इस स्पॉट का अभ्यास करें", practiceBusy: "अभ्यास के सवाल बनाए जा रहे हैं…", practiceUnavailable: "अभ्यास के सवाल नहीं बन सकते: आपकी रेंज का कोई हैंड इस स्पॉट तक नहीं पहुँचता, हर एक्शन का EV उपलब्ध नहीं है, या चुनने के लिए सिर्फ़ एक ही एक्शन है।", practiceReferenceNote: "यह स्पॉट बहुत कम बार आता है, इसलिए इसके मान भरोसेमंद नहीं हैं। इसे सिर्फ़ संदर्भ के लिए देखें; यह गलतियों के रिव्यू में नहीं जोड़ा जाता।", practiceError: "अभ्यास के सवाल सहेजे नहीं जा सके। फिर से कोशिश करें।",
  },
  tr: {
    title: "El analizi", situation: "Durum", hero: "Senin pozisyonun", opener: "Açan pozisyon", caller: "Call eden pozisyon", threeBettor: "3-bet yapan pozisyon", preflop: "Preflop",
    singleRaised: "Open · Call", threeBet: "3-bet pot", multiway: "3+ oyuncu", notSupported: "Analiz edilemez",
    unavailableScenario: "Bu durumun verisi henüz hazır değil.", fileMissing: "Bu flop için sonuç dosyası yok.",
    loadFailed: "Sonuç dosyası yüklenemedi.", invalidData: "Sonuç dosyası okunamadı.",
    unsupportedAction: "Bu aksiyon analiz edilemez.", unsupportedSize: "Bu boyut analiz edilemez.",
    evMissing: "EV yok", referenceOnly: "Yalnızca referans", mixedAction: "Solver da kullanıyor",
    precomputed: "Önceden hesaplanmış sonuç", onDevice: "Bu cihazda hesaplandı", flop: "Flop", turn: "Turn", river: "River",
    chooseHand: "2 kartın", chooseFlop: "3 flop kartı", chooseTurn: "Turn kartı", chooseRiver: "River kartı",
    result: "Sonuçlar", totalLoss: "Toplam kayıp",
    best: "En iyi oyun", good: "Kabul edilebilir", mistake: "Bu oyunu tekrar incele",
    noResults: "Sonuçları görmek için kartlarını seç ve aksiyonları gir.", chooseAction: "Oynanan aksiyonu seç.",
    opponentResponse: "Rakibin senin oyununa cevabı", foldingHands: "Fold eden eller",
    handGrid: "El tablosu", matchedSize: "Boyut eşlendi {actual} → {used}",
    undo: "Geri al", newHand: "Yeni el", loading: "Veri yükleniyor…", solving: "Hesaplanıyor…",
    solveFailed: "Bu street'in hesaplaması bitirilemedi.", retry: "Tekrar dene", complete: "El bitti",
    check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise", allin: "All-in",
    scopeNote: "Ücretsiz · Online 6-max cash, 100bb. Sonuçlar bar oyunlarına veya turnuvalara uymayabilir. 3-bet pot'lar hazırlanıyor; multiway pot'lar analiz edilemez.",
    referenceNote: "Ulaşma payları çarpımı {threshold} altında kalan spot'lar hata sayısına ve toplam kayba dahil edilmez.",
    evMissingNote: "Kaybı değerlendirmek için EV yok. Yalnızca sıklıklar gösteriliyor.", reach: "Ulaşma payları çarpımı",
    pot: "Pot", heroOutsideRange: "Bu el, seçilen pozisyonun varsayılan range'inin dışında.",
    hand: "Elin",
    navTitle: "El analizi", cancel: "İptal",
    noCompatibleHands: "Bu spot'ta kartlarınla çakışmayan bir rakip eli yok.", otherSize: "Diğer boyut",
    unanalysed: "Analiz edilmedi", scopeTitle: "Analiz varsayımları",
    practiceSpot: "Bu spot'u çalış", practiceBusy: "Pratik soruları hazırlanıyor…", practiceUnavailable: "Pratik soruları oluşturulamıyor: range'indeki hiçbir el bu spot'a ulaşmıyor, aksiyon başına EV'ler eksik ya da seçilecek tek bir aksiyon var.", practiceReferenceNote: "Bu spot'a çok nadir ulaşılıyor, değerler güvenilir değil. Yalnızca referans olarak kullan; hata tekrarına eklenmez.", practiceError: "Pratik soruları kaydedilemedi. Tekrar dene.",
  },
} as const;

export type HandReviewLabelKey = keyof typeof M.en;
export type HandReviewLabels = Record<HandReviewLabelKey, string>;
// This assignment checks both the locale set and every required key at build time.
const checkedLabels: LocaleDict<HandReviewLabels> = M;
export const handReviewLabels = (locale: Locale): HandReviewLabels => checkedLabels[locale];
