import { i18n, Locale } from "./i18n";

type NodeLockMessages = {
  title: string;
  apply: string;
  clearAll: string;
  remove: string;
  before: string;
  after: string;
  frequency: string;
  comparison: string;
  exploitability: string;
  sumError: string;
  skippedChance: string;
  engineError: string;
  assumption: string;
  banner: string;
  noReach: string;
};

// AI-written drafts. Keep every locale and key in the A1b review ledger.
export const NODE_LOCK_MESSAGES: Record<Locale, NodeLockMessages> = {
  ko: {
    title: "이 노드의 전략 고정",
    apply: "고정하고 다시 풀기",
    clearAll: "전체 해제하고 다시 풀기",
    remove: "해제하고 다시 풀기",
    before: "고정 전",
    after: "고정 후",
    frequency: "빈도",
    comparison: "고정 전/후 비교",
    exploitability: "오차(exploitability)",
    sumError: "액션마다 0–100의 정수를 입력하고 합계를 100으로 맞춰 주세요.",
    skippedChance: "카드를 지정하지 않고 건너뛴 경로는 고정할 수 없습니다. 카드를 먼저 선택해 주세요.",
    engineError: "전략을 고정하지 못했습니다. 입력값을 확인하고 다시 풀어 주세요.",
    assumption: "고정 가정 하의 값",
    banner: "상대 전략을 고정한 착취 전략 — 균형(GTO) 전략이 아니다 · 고정 노드 {count}개",
    noReach: "이 노드의 도달 가중치가 0이어서 초기 빈도를 표시할 수 없습니다.",
  },
  en: {
    title: "Lock this node’s strategy",
    apply: "Lock and solve again",
    clearAll: "Unlock all and solve again",
    remove: "Unlock and solve again",
    before: "Before locking",
    after: "After locking",
    frequency: "Frequency",
    comparison: "Before/after comparison",
    exploitability: "Exploitability",
    sumError: "Enter integers from 0 to 100 for each action, totaling 100.",
    skippedChance: "A path with an unspecified card cannot be locked. Select the card first.",
    engineError: "The strategy could not be locked. Check the input values and solve again.",
    assumption: "Values under the fixed-strategy assumption",
    banner: "Exploitative strategy with the opponent’s strategy fixed — not an equilibrium (GTO) strategy · {count} locked nodes",
    noReach: "This node’s reach weight is 0, so initial frequencies are unavailable.",
  },
  ja: {
    title: "このノードの戦略を固定",
    apply: "固定して再計算",
    clearAll: "全解除して再計算",
    remove: "解除して再計算",
    before: "固定前",
    after: "固定後",
    frequency: "頻度",
    comparison: "固定前後の比較",
    exploitability: "誤差(exploitability)",
    sumError: "各アクションは0～100の整数、合計100にしてください。",
    skippedChance: "カード未指定の経路は固定できません。カードを選んでください。",
    engineError: "戦略を固定できませんでした。入力を確認して再計算してください。",
    assumption: "固定条件下の値",
    banner: "相手戦略を固定した搾取戦略 — 均衡（GTO）戦略ではありません · 固定ノード{count}個",
    noReach: "このノードの到達ウェイトは0です。初期頻度を表示できません。",
  },
  es: {
    title: "Fijar la estrategia de este nodo",
    apply: "Fijar y recalcular",
    clearAll: "Quitar todas y recalcular",
    remove: "Quitar y recalcular",
    before: "Antes de fijar",
    after: "Después de fijar",
    frequency: "Frecuencia",
    comparison: "Comparación antes/después",
    exploitability: "Exploitability",
    sumError: "Introduce enteros de 0 a 100 para cada acción, con un total de 100.",
    skippedChance: "No se puede fijar una ruta con una carta sin elegir. Elige primero la carta.",
    engineError: "No se pudo fijar la estrategia. Revisa los valores y vuelve a calcular.",
    assumption: "Valores bajo el supuesto de estrategia fija",
    banner: "Estrategia explotadora con la estrategia rival fijada — no es una estrategia de equilibrio (GTO) · {count} nodos fijados",
    noReach: "El peso de llegada a este nodo es 0; las frecuencias iniciales no están disponibles.",
  },
  pt: {
    title: "Fixar a estratégia deste nó",
    apply: "Fixar e calcular de novo",
    clearAll: "Remover todas e calcular de novo",
    remove: "Remover e calcular de novo",
    before: "Antes de fixar",
    after: "Depois de fixar",
    frequency: "Frequência",
    comparison: "Comparação antes/depois",
    exploitability: "Exploitability",
    sumError: "Insira números inteiros de 0 a 100 para cada ação, com um total de 100.",
    skippedChance: "Não é possível fixar um caminho com uma carta não escolhida. Escolha a carta primeiro.",
    engineError: "Não foi possível fixar a estratégia. Confira os valores e calcule de novo.",
    assumption: "Valores sob a hipótese de estratégia fixa",
    banner: "Estratégia exploradora com a estratégia do adversário fixada — não é uma estratégia de equilíbrio (GTO) · {count} nós fixados",
    noReach: "O peso de chegada a este nó é 0; as frequências iniciais não estão disponíveis.",
  },
  de: {
    title: "Strategie dieses Knotens fixieren",
    apply: "Fixieren und neu berechnen",
    clearAll: "Alle lösen und neu berechnen",
    remove: "Lösen und neu berechnen",
    before: "Vor der Fixierung",
    after: "Nach der Fixierung",
    frequency: "Häufigkeit",
    comparison: "Vorher/Nachher-Vergleich",
    exploitability: "Exploitability",
    sumError: "Gib für jede Aktion ganze Zahlen von 0 bis 100 ein, mit einer Summe von 100.",
    skippedChance: "Ein Pfad mit einer nicht gewählten Karte kann nicht fixiert werden. Wähle zuerst die Karte.",
    engineError: "Die Strategie konnte nicht fixiert werden. Prüfe die Werte und berechne erneut.",
    assumption: "Werte unter der Annahme einer fixierten Strategie",
    banner: "Exploitative Strategie bei fixierter gegnerischer Strategie – keine Gleichgewichtsstrategie (GTO) · {count} fixierte Knoten",
    noReach: "Das Erreichungsgewicht dieses Knotens ist 0; anfängliche Häufigkeiten sind nicht verfügbar.",
  },
  zh: {
    title: "固定此节点的策略",
    apply: "固定并重新计算",
    clearAll: "全部解除并重新计算",
    remove: "解除并重新计算",
    before: "固定前",
    after: "固定后",
    frequency: "频率",
    comparison: "固定前后对比",
    exploitability: "可剥削度",
    sumError: "每个行动请输入0至100的整数，总和须为100。",
    skippedChance: "路径中有未指定的牌，无法固定策略。请先选择牌。",
    engineError: "无法固定策略。请检查输入值后重新计算。",
    assumption: "固定策略假设下的数值",
    banner: "固定对手策略的剥削策略——不是均衡（GTO）策略 · 已固定节点：{count}",
    noReach: "此节点的到达权重为0，无法显示初始频率。",
  },
  "zh-hant": {
    title: "固定此節點的策略",
    apply: "固定並重新計算",
    clearAll: "全部解除並重新計算",
    remove: "解除並重新計算",
    before: "固定前",
    after: "固定後",
    frequency: "頻率",
    comparison: "固定前後比較",
    exploitability: "可剝削度",
    sumError: "每個行動請輸入0至100的整數，總和須為100。",
    skippedChance: "路徑中有未指定的牌，無法固定策略。請先選擇牌。",
    engineError: "無法固定策略。請檢查輸入值後重新計算。",
    assumption: "固定策略假設下的數值",
    banner: "固定對手策略的剝削策略——不是均衡（GTO）策略 · 已固定節點：{count}",
    noReach: "此節點的到達權重為0，無法顯示初始頻率。",
  },
  fr: {
    title: "Fixer la stratégie de ce nœud",
    apply: "Fixer et recalculer",
    clearAll: "Tout libérer et recalculer",
    remove: "Libérer et recalculer",
    before: "Avant fixation",
    after: "Après fixation",
    frequency: "Fréquence",
    comparison: "Comparaison avant/après",
    exploitability: "Exploitabilité",
    sumError: "Saisis des entiers de 0 à 100 pour chaque action, avec un total de 100.",
    skippedChance: "Un chemin avec une carte non choisie ne peut pas être fixé. Choisis d’abord la carte.",
    engineError: "La stratégie n’a pas pu être fixée. Vérifie les valeurs, puis relance le calcul.",
    assumption: "Valeurs sous l’hypothèse d’une stratégie fixée",
    banner: "Stratégie d’exploitation avec stratégie adverse fixée — ce n’est pas une stratégie d’équilibre (GTO) · {count} nœuds fixés",
    noReach: "Le poids d’atteinte de ce nœud est de 0 ; les fréquences initiales ne sont pas disponibles.",
  },
  id: {
    title: "Kunci strategi di node ini",
    apply: "Kunci dan hitung ulang",
    clearAll: "Buka semua kunci dan hitung ulang",
    remove: "Buka kunci dan hitung ulang",
    before: "Sebelum dikunci",
    after: "Sesudah dikunci",
    frequency: "Frekuensi",
    comparison: "Perbandingan sebelum/sesudah",
    exploitability: "Exploitability",
    sumError: "Gunakan bilangan bulat 0–100 untuk tiap aksi, dengan total 100.",
    skippedChance: "Strategi pada jalur dengan kartu yang belum dipilih tidak dapat dikunci. Pilih kartunya terlebih dahulu.",
    engineError: "Strategi tidak dapat dikunci. Periksa nilai input, lalu hitung ulang.",
    assumption: "Nilai dengan asumsi strategi yang dikunci",
    banner: "Strategi eksploitatif dengan strategi lawan dikunci — bukan strategi ekuilibrium (GTO) · {count} node dikunci",
    noReach: "Bobot untuk mencapai node ini adalah 0; frekuensi awal tidak tersedia.",
  },
  ms: {
    title: "Kunci strategi pada nod ini",
    apply: "Kunci dan kira semula",
    clearAll: "Nyahkunci semua dan kira semula",
    remove: "Nyahkunci dan kira semula",
    before: "Sebelum dikunci",
    after: "Selepas dikunci",
    frequency: "Kekerapan",
    comparison: "Perbandingan sebelum/selepas",
    exploitability: "Exploitability",
    sumError: "Gunakan integer 0–100 bagi setiap tindakan, dengan jumlah 100.",
    skippedChance: "Strategi pada laluan dengan kad yang belum dipilih tidak boleh dikunci. Pilih kad dahulu.",
    engineError: "Strategi tidak dapat dikunci. Semak nilai input dan kira semula.",
    assumption: "Nilai berdasarkan andaian strategi dikunci",
    banner: "Strategi eksploitatif dengan strategi lawan dikunci — bukan strategi keseimbangan (GTO) · {count} nod dikunci",
    noReach: "Pemberat untuk mencapai nod ini ialah 0; kekerapan awal tidak tersedia.",
  },
  hi: {
    title: "इस नोड की रणनीति लॉक करें",
    apply: "रणनीति लॉक करके फिर गणना करें",
    clearAll: "सभी लॉक हटाकर फिर गणना करें",
    remove: "लॉक हटाकर फिर गणना करें",
    before: "लॉक करने से पहले",
    after: "लॉक करने के बाद",
    frequency: "फ़्रीक्वेंसी",
    comparison: "पहले और बाद की तुलना",
    exploitability: "Exploitability",
    sumError: "हर action के लिए 0–100 का पूर्णांक दें। कुल 100 होना चाहिए।",
    skippedChance: "बिना कार्ड चुने आगे बढ़े रास्ते की रणनीति लॉक नहीं कर सकते। पहले कार्ड चुनें।",
    engineError: "रणनीति लॉक नहीं हो सकी। मान जाँचकर फिर गणना करें।",
    assumption: "लॉक की गई रणनीति की मान्यता के तहत मान",
    banner: "प्रतिद्वंद्वी की रणनीति लॉक करने पर बनी exploitative रणनीति — यह संतुलन (GTO) रणनीति नहीं है · {count} लॉक किए गए नोड",
    noReach: "इस नोड तक पहुँचने का वज़न 0 है; शुरुआती फ़्रीक्वेंसी उपलब्ध नहीं है।",
  },
};

export const nodeLockLabels = () => NODE_LOCK_MESSAGES[i18n.locale];
