/**
 * F1 approved form/error copy: ../Holdem_Project/lib/solver-reviews-i18n.ts.
 * Do not rephrase. Regenerate with: node 도구/e2e/feedback-copy-labels.js
 * App-only copy is a separate dictionary below the generated block.
 */
import type { LocaleDict } from "./i18n";

export type FeedbackLabels = {
  formTitle: string;
  tabReview: string;
  ratingLabel: string;
  placeholderReview: string;
  downsideToggle: string;
  downsidePlaceholder: string;
  postingAs: (name: string) => string;
  change: string;
  nicknameSave: string;
  nicknameCancel: string;
  nicknameEmailWarn: string;
  submit: string;
  submitEdit: string;
  loginTitle: string;
  loginGoogle: string;
  loginKakao: string;
  linkWarn: string;
  saved: string;
  errors: Record<string, string>;
};

export const feedbackLabels: LocaleDict<FeedbackLabels> = {
  ko: {
    formTitle: "솔버 써 보니 어땠나요?",
    tabReview: "후기",
    ratingLabel: "별점 (선택)",
    placeholderReview: "한마디 남겨 주세요 — 좋았던 점도 아쉬운 점도 그대로",
    downsideToggle: "+ 아쉬운 점도 적기",
    downsidePlaceholder: "아쉬웠던 점 (선택)",
    postingAs: (name) => `${name} 으로 남깁니다`,
    change: "바꾸기",
    nicknameSave: "이름 저장",
    nicknameCancel: "취소",
    nicknameEmailWarn: "지금 이름이 이메일 앞부분입니다. 공개되기 전에 이름을 먼저 정해 주세요.",
    submit: "남기기",
    submitEdit: "수정하기",
    loginTitle: "로그인하면 쓴 글이 그대로 올라갑니다",
    loginGoogle: "구글로 계속",
    loginKakao: "카카오로 계속",
    linkWarn: "링크는 넣을 수 없어요",
    saved: "남겼습니다. 고마워요!",
    errors: {
    login: "로그인이 필요합니다.",
    unavailable: "잠시 후 다시 시도해 주세요.",
    body_short: "한마디만 남겨 주세요 (2자 이상).",
    body_long: "600자까지 쓸 수 있습니다.",
    downside_long: "아쉬운 점은 200자까지입니다.",
    link: "링크는 넣을 수 없어요.",
    rating: "별점 값이 올바르지 않습니다.",
    rating_needs_body: "한마디만 남겨 주세요 — 글 없이 별점만은 받지 않습니다.",
    rate: "잠시 후 다시 남겨 주세요.",
    nickname_confirm: "남기기 전에 이름을 정해 주세요.",
    nickname_short: "이름은 2자 이상입니다.",
    nickname_long: "이름은 20자까지입니다.",
    nickname_link: "이름에 주소·이메일은 쓸 수 없습니다.",
    nickname_impersonation: "운영자·공식으로 보이는 이름은 쓸 수 없습니다.",
    image_type: "이미지 파일(jpg·png·webp)만 올릴 수 있습니다.",
    image_size: "5MB 이하 이미지를 올려 주세요.",
    already_requested: "이미 검토를 요청했습니다.",
    not_found: "찾지 못했습니다. 새로고침해 주세요.",
    bad_input: "잠시 후 다시 시도해 주세요.",
    locale: "잠시 후 다시 시도해 주세요.",
  },
  },
  en: {
    formTitle: "How was the solver for you?",
    tabReview: "Review",
    ratingLabel: "Rating (optional)",
    placeholderReview: "Leave a few words — the good and the bad, as it is",
    downsideToggle: "+ Add what could be better",
    downsidePlaceholder: "What could be better (optional)",
    postingAs: (name) => `Posting as ${name}`,
    change: "Change",
    nicknameSave: "Save name",
    nicknameCancel: "Cancel",
    nicknameEmailWarn: "Your name is currently the first part of your email. Please choose a name before it goes public.",
    submit: "Post",
    submitEdit: "Update",
    loginTitle: "Sign in and your text is posted as written",
    loginGoogle: "Continue with Google",
    loginKakao: "Continue with Kakao",
    linkWarn: "Links can't be included",
    saved: "Posted. Thank you!",
    errors: {
    login: "Please sign in.",
    unavailable: "Please try again in a moment.",
    body_short: "Please write at least a couple of characters.",
    body_long: "Up to 600 characters.",
    downside_long: "Up to 200 characters for what could be better.",
    link: "Links can't be included.",
    rating: "Invalid rating.",
    rating_needs_body: "Please add a few words — we don't take ratings without text.",
    rate: "Please try again in a few minutes.",
    nickname_confirm: "Please choose a name before posting.",
    nickname_short: "Names need at least 2 characters.",
    nickname_long: "Names can be up to 20 characters.",
    nickname_link: "Names can't contain addresses or emails.",
    nickname_impersonation: "Names that look official or like staff aren't allowed.",
    image_type: "Only image files (jpg, png, webp).",
    image_size: "Please upload an image under 5 MB.",
    already_requested: "You've already asked for another look.",
    not_found: "Not found. Please refresh.",
    bad_input: "Please try again in a moment.",
    locale: "Please try again in a moment.",
  },
  },
  ja: {
    formTitle: "ソルバーを使ってみてどうでしたか？",
    tabReview: "レビュー",
    ratingLabel: "評価（任意）",
    placeholderReview: "ひとことどうぞ — 良かった点も気になった点もそのまま",
    downsideToggle: "+ 気になった点も書く",
    downsidePlaceholder: "気になった点（任意）",
    postingAs: (name) => `${name} として投稿します`,
    change: "変更",
    nicknameSave: "名前を保存",
    nicknameCancel: "キャンセル",
    nicknameEmailWarn: "現在の名前はメールアドレスの前半です。公開される前に名前を決めてください。",
    submit: "投稿する",
    submitEdit: "更新する",
    loginTitle: "ログインすると、書いた内容がそのまま投稿されます",
    loginGoogle: "Googleで続ける",
    loginKakao: "Kakaoで続ける",
    linkWarn: "リンクは入れられません",
    saved: "投稿しました。ありがとうございます！",
    errors: {
    login: "ログインが必要です。",
    unavailable: "しばらくしてから再度お試しください。",
    body_short: "ひとことだけでも書いてください（2文字以上）。",
    body_long: "600文字までです。",
    downside_long: "気になった点は200文字までです。",
    link: "リンクは入れられません。",
    rating: "評価の値が正しくありません。",
    rating_needs_body: "ひとこと添えてください — 評価だけの投稿は受け付けていません。",
    rate: "少し時間をおいてから投稿してください。",
    nickname_confirm: "投稿する前に名前を決めてください。",
    nickname_short: "名前は2文字以上です。",
    nickname_long: "名前は20文字までです。",
    nickname_link: "名前にアドレス・メールは使えません。",
    nickname_impersonation: "運営・公式に見える名前は使えません。",
    image_type: "画像ファイル（jpg・png・webp）のみです。",
    image_size: "5MB以下の画像をアップロードしてください。",
    already_requested: "すでに再確認を依頼しています。",
    not_found: "見つかりません。再読み込みしてください。",
    bad_input: "しばらくしてから再度お試しください。",
    locale: "しばらくしてから再度お試しください。",
  },
  },
  es: {
    formTitle: "¿Qué te pareció el solver?",
    tabReview: "Opinión",
    ratingLabel: "Valoración (opcional)",
    placeholderReview: "Deja unas palabras — lo bueno y lo malo, tal cual",
    downsideToggle: "+ Añadir lo que se puede mejorar",
    downsidePlaceholder: "Lo que se puede mejorar (opcional)",
    postingAs: (name) => `Publicarás como ${name}`,
    change: "Cambiar",
    nicknameSave: "Guardar nombre",
    nicknameCancel: "Cancelar",
    nicknameEmailWarn: "Tu nombre ahora es la primera parte de tu correo. Elige un nombre antes de que se publique.",
    submit: "Publicar",
    submitEdit: "Actualizar",
    loginTitle: "Inicia sesión y tu texto se publica tal como lo escribiste",
    loginGoogle: "Continuar con Google",
    loginKakao: "Continuar con Kakao",
    linkWarn: "No se pueden incluir enlaces",
    saved: "Publicado. ¡Gracias!",
    errors: {
    login: "Inicia sesión, por favor.",
    unavailable: "Inténtalo de nuevo en un momento.",
    body_short: "Escribe al menos un par de caracteres.",
    body_long: "Hasta 600 caracteres.",
    downside_long: "Hasta 200 caracteres en lo que se puede mejorar.",
    link: "No se pueden incluir enlaces.",
    rating: "Valoración no válida.",
    rating_needs_body: "Añade unas palabras — no aceptamos valoraciones sin texto.",
    rate: "Inténtalo de nuevo en unos minutos.",
    nickname_confirm: "Elige un nombre antes de publicar.",
    nickname_short: "El nombre necesita al menos 2 caracteres.",
    nickname_long: "El nombre admite hasta 20 caracteres.",
    nickname_link: "El nombre no puede contener direcciones ni correos.",
    nickname_impersonation: "No se permiten nombres que parezcan oficiales o del equipo.",
    image_type: "Solo archivos de imagen (jpg, png, webp).",
    image_size: "Sube una imagen de menos de 5 MB.",
    already_requested: "Ya pediste otra revisión.",
    not_found: "No se encontró. Recarga la página.",
    bad_input: "Inténtalo de nuevo en un momento.",
    locale: "Inténtalo de nuevo en un momento.",
  },
  },
  pt: {
    formTitle: "O que você achou do solver?",
    tabReview: "Avaliação",
    ratingLabel: "Nota (opcional)",
    placeholderReview: "Deixe algumas palavras — o bom e o ruim, do jeito que foi",
    downsideToggle: "+ Contar o que pode melhorar",
    downsidePlaceholder: "O que pode melhorar (opcional)",
    postingAs: (name) => `Publicando como ${name}`,
    change: "Mudar",
    nicknameSave: "Salvar nome",
    nicknameCancel: "Cancelar",
    nicknameEmailWarn: "Seu nome agora é a primeira parte do seu e-mail. Escolha um nome antes de ele ficar público.",
    submit: "Publicar",
    submitEdit: "Atualizar",
    loginTitle: "Entre e seu texto é publicado do jeito que você escreveu",
    loginGoogle: "Continuar com Google",
    loginKakao: "Continuar com Kakao",
    linkWarn: "Não é possível incluir links",
    saved: "Publicado. Obrigado!",
    errors: {
    login: "Faça login, por favor.",
    unavailable: "Tente de novo em instantes.",
    body_short: "Escreva pelo menos alguns caracteres.",
    body_long: "Até 600 caracteres.",
    downside_long: "Até 200 caracteres no que pode melhorar.",
    link: "Não é possível incluir links.",
    rating: "Nota inválida.",
    rating_needs_body: "Escreva algumas palavras — não aceitamos nota sem texto.",
    rate: "Tente de novo em alguns minutos.",
    nickname_confirm: "Escolha um nome antes de publicar.",
    nickname_short: "O nome precisa de pelo menos 2 caracteres.",
    nickname_long: "O nome pode ter até 20 caracteres.",
    nickname_link: "O nome não pode conter endereços nem e-mails.",
    nickname_impersonation: "Não são permitidos nomes que pareçam oficiais ou da equipe.",
    image_type: "Só arquivos de imagem (jpg, png, webp).",
    image_size: "Envie uma imagem com menos de 5 MB.",
    already_requested: "Você já pediu uma nova revisão.",
    not_found: "Não encontrado. Recarregue a página.",
    bad_input: "Tente de novo em instantes.",
    locale: "Tente de novo em instantes.",
  },
  },
  de: {
    formTitle: "Wie fandest du den Solver?",
    tabReview: "Bewertung",
    ratingLabel: "Sterne (optional)",
    placeholderReview: "Schreib ein paar Worte — Gutes wie Schlechtes, so wie es war",
    downsideToggle: "+ Was besser sein könnte",
    downsidePlaceholder: "Was besser sein könnte (optional)",
    postingAs: (name) => `Du postest als ${name}`,
    change: "Ändern",
    nicknameSave: "Namen speichern",
    nicknameCancel: "Abbrechen",
    nicknameEmailWarn: "Dein Name ist gerade der vordere Teil deiner E-Mail-Adresse. Bitte wähle einen Namen, bevor er öffentlich wird.",
    submit: "Posten",
    submitEdit: "Aktualisieren",
    loginTitle: "Nach dem Anmelden wird dein Text so gepostet, wie du ihn geschrieben hast",
    loginGoogle: "Weiter mit Google",
    loginKakao: "Weiter mit Kakao",
    linkWarn: "Links sind nicht möglich",
    saved: "Gepostet. Danke!",
    errors: {
    login: "Bitte melde dich an.",
    unavailable: "Bitte versuch es gleich noch einmal.",
    body_short: "Bitte schreib mindestens zwei Zeichen.",
    body_long: "Höchstens 600 Zeichen.",
    downside_long: "Höchstens 200 Zeichen für Verbesserungen.",
    link: "Links sind nicht möglich.",
    rating: "Ungültige Bewertung.",
    rating_needs_body: "Bitte schreib ein paar Worte — Sterne ohne Text nehmen wir nicht an.",
    rate: "Bitte versuch es in ein paar Minuten noch einmal.",
    nickname_confirm: "Bitte wähle vor dem Posten einen Namen.",
    nickname_short: "Der Name braucht mindestens 2 Zeichen.",
    nickname_long: "Der Name darf höchstens 20 Zeichen haben.",
    nickname_link: "Der Name darf keine Adressen oder E-Mails enthalten.",
    nickname_impersonation: "Namen, die offiziell oder nach Team aussehen, sind nicht erlaubt.",
    image_type: "Nur Bilddateien (jpg, png, webp).",
    image_size: "Bitte lade ein Bild unter 5 MB hoch.",
    already_requested: "Du hast bereits eine erneute Prüfung angefragt.",
    not_found: "Nicht gefunden. Bitte neu laden.",
    bad_input: "Bitte versuch es gleich noch einmal.",
    locale: "Bitte versuch es gleich noch einmal.",
  },
  },
  zh: {
    formTitle: "用了求解器，感觉怎么样？",
    tabReview: "评价",
    ratingLabel: "评分（可选）",
    placeholderReview: "说一句吧 — 好的不好的都可以照实写",
    downsideToggle: "+ 也写写不足之处",
    downsidePlaceholder: "不足之处（可选）",
    postingAs: (name) => `将以 ${name} 的名义发布`,
    change: "修改",
    nicknameSave: "保存名字",
    nicknameCancel: "取消",
    nicknameEmailWarn: "你现在的名字是邮箱前缀。公开之前请先设定一个名字。",
    submit: "发布",
    submitEdit: "更新",
    loginTitle: "登录后，你写的内容会原样发布",
    loginGoogle: "使用 Google 继续",
    loginKakao: "使用 Kakao 继续",
    linkWarn: "不能包含链接",
    saved: "已发布，谢谢！",
    errors: {
    login: "请先登录。",
    unavailable: "请稍后再试。",
    body_short: "请至少写两个字。",
    body_long: "最多 600 字。",
    downside_long: "不足之处最多 200 字。",
    link: "不能包含链接。",
    rating: "评分无效。",
    rating_needs_body: "请写一句话 — 不接受只有评分的提交。",
    rate: "请过几分钟再发布。",
    nickname_confirm: "发布前请先设定名字。",
    nickname_short: "名字至少 2 个字。",
    nickname_long: "名字最多 20 个字。",
    nickname_link: "名字不能包含网址或邮箱。",
    nickname_impersonation: "不能使用看起来像官方或管理员的名字。",
    image_type: "仅限图片文件（jpg、png、webp）。",
    image_size: "请上传 5MB 以下的图片。",
    already_requested: "已经申请过重新审核。",
    not_found: "未找到，请刷新页面。",
    bad_input: "请稍后再试。",
    locale: "请稍后再试。",
  },
  },
  "zh-hant": {
    formTitle: "用了求解器，感覺如何？",
    tabReview: "評價",
    ratingLabel: "評分（選填）",
    placeholderReview: "留一句話吧 — 好的不好的都可以照實寫",
    downsideToggle: "+ 也寫寫不足之處",
    downsidePlaceholder: "不足之處（選填）",
    postingAs: (name) => `將以 ${name} 的名義發布`,
    change: "修改",
    nicknameSave: "儲存名稱",
    nicknameCancel: "取消",
    nicknameEmailWarn: "你目前的名稱是電子郵件前綴。公開之前請先設定名稱。",
    submit: "發布",
    submitEdit: "更新",
    loginTitle: "登入後，你寫的內容會原樣發布",
    loginGoogle: "使用 Google 繼續",
    loginKakao: "使用 Kakao 繼續",
    linkWarn: "不能包含連結",
    saved: "已發布，謝謝！",
    errors: {
    login: "請先登入。",
    unavailable: "請稍後再試。",
    body_short: "請至少寫兩個字。",
    body_long: "最多 600 字。",
    downside_long: "不足之處最多 200 字。",
    link: "不能包含連結。",
    rating: "評分無效。",
    rating_needs_body: "請寫一句話 — 不接受只有評分的提交。",
    rate: "請過幾分鐘再發布。",
    nickname_confirm: "發布前請先設定名稱。",
    nickname_short: "名稱至少 2 個字。",
    nickname_long: "名稱最多 20 個字。",
    nickname_link: "名稱不能包含網址或電子郵件。",
    nickname_impersonation: "不能使用看起來像官方或管理員的名稱。",
    image_type: "僅限圖片檔（jpg、png、webp）。",
    image_size: "請上傳 5MB 以下的圖片。",
    already_requested: "已經申請過重新審核。",
    not_found: "找不到，請重新整理頁面。",
    bad_input: "請稍後再試。",
    locale: "請稍後再試。",
  },
  },
  fr: {
    formTitle: "Qu'as-tu pensé du solver ?",
    tabReview: "Avis",
    ratingLabel: "Note (facultatif)",
    placeholderReview: "Laisse quelques mots — le bon comme le moins bon, tel quel",
    downsideToggle: "+ Ajouter ce qui pourrait être mieux",
    downsidePlaceholder: "Ce qui pourrait être mieux (facultatif)",
    postingAs: (name) => `Publié sous le nom ${name}`,
    change: "Modifier",
    nicknameSave: "Enregistrer le nom",
    nicknameCancel: "Annuler",
    nicknameEmailWarn: "Ton nom est actuellement le début de ton adresse e-mail. Choisis un nom avant qu'il soit public.",
    submit: "Publier",
    submitEdit: "Mettre à jour",
    loginTitle: "Connecte-toi et ton texte est publié tel que tu l'as écrit",
    loginGoogle: "Continuer avec Google",
    loginKakao: "Continuer avec Kakao",
    linkWarn: "Les liens ne sont pas autorisés",
    saved: "Publié. Merci !",
    errors: {
    login: "Connecte-toi, s'il te plaît.",
    unavailable: "Réessaie dans un instant.",
    body_short: "Écris au moins deux caractères.",
    body_long: "600 caractères maximum.",
    downside_long: "200 caractères maximum pour ce qui pourrait être mieux.",
    link: "Les liens ne sont pas autorisés.",
    rating: "Note invalide.",
    rating_needs_body: "Ajoute quelques mots — nous n'acceptons pas de note sans texte.",
    rate: "Réessaie dans quelques minutes.",
    nickname_confirm: "Choisis un nom avant de publier.",
    nickname_short: "Le nom doit comporter au moins 2 caractères.",
    nickname_long: "Le nom ne peut pas dépasser 20 caractères.",
    nickname_link: "Le nom ne peut pas contenir d'adresse ni d'e-mail.",
    nickname_impersonation: "Les noms qui ressemblent à un compte officiel ou à l'équipe ne sont pas autorisés.",
    image_type: "Fichiers image uniquement (jpg, png, webp).",
    image_size: "Importe une image de moins de 5 Mo.",
    already_requested: "Tu as déjà demandé un nouvel examen.",
    not_found: "Introuvable. Recharge la page.",
    bad_input: "Réessaie dans un instant.",
    locale: "Réessaie dans un instant.",
  },
  },
  id: {
    formTitle: "Bagaimana pengalaman Anda memakai solver?",
    tabReview: "Ulasan",
    ratingLabel: "Rating (opsional)",
    placeholderReview: "Tulis sepatah kata — yang bagus maupun yang kurang, apa adanya",
    downsideToggle: "+ Tulis juga yang kurang",
    downsidePlaceholder: "Yang kurang (opsional)",
    postingAs: (name) => `Dikirim sebagai ${name}`,
    change: "Ganti",
    nicknameSave: "Simpan nama",
    nicknameCancel: "Batal",
    nicknameEmailWarn: "Nama Anda saat ini adalah bagian depan email Anda. Tentukan nama dulu sebelum tampil publik.",
    submit: "Kirim",
    submitEdit: "Perbarui",
    loginTitle: "Masuk, lalu tulisan Anda langsung terkirim apa adanya",
    loginGoogle: "Lanjutkan dengan Google",
    loginKakao: "Lanjutkan dengan Kakao",
    linkWarn: "Tautan tidak bisa dimasukkan",
    saved: "Terkirim. Terima kasih!",
    errors: {
    login: "Silakan masuk.",
    unavailable: "Coba lagi sebentar lagi.",
    body_short: "Tulis setidaknya dua karakter.",
    body_long: "Maksimal 600 karakter.",
    downside_long: "Bagian yang kurang maksimal 200 karakter.",
    link: "Tautan tidak bisa dimasukkan.",
    rating: "Rating tidak valid.",
    rating_needs_body: "Tambahkan sepatah kata — rating tanpa tulisan tidak kami terima.",
    rate: "Coba lagi beberapa menit lagi.",
    nickname_confirm: "Tentukan nama sebelum mengirim.",
    nickname_short: "Nama minimal 2 karakter.",
    nickname_long: "Nama maksimal 20 karakter.",
    nickname_link: "Nama tidak boleh berisi alamat atau email.",
    nickname_impersonation: "Nama yang terlihat resmi atau seperti tim tidak diizinkan.",
    image_type: "Hanya file gambar (jpg, png, webp).",
    image_size: "Unggah gambar di bawah 5 MB.",
    already_requested: "Anda sudah meminta peninjauan ulang.",
    not_found: "Tidak ditemukan. Muat ulang halaman.",
    bad_input: "Coba lagi sebentar lagi.",
    locale: "Coba lagi sebentar lagi.",
  },
  },
  ms: {
    formTitle: "Bagaimana pengalaman anda menggunakan solver?",
    tabReview: "Ulasan",
    ratingLabel: "Penilaian (pilihan)",
    placeholderReview: "Tinggalkan sepatah dua kata — yang baik dan yang kurang, seadanya",
    downsideToggle: "+ Tulis juga yang kurang",
    downsidePlaceholder: "Yang kurang (pilihan)",
    postingAs: (name) => `Dihantar sebagai ${name}`,
    change: "Tukar",
    nicknameSave: "Simpan nama",
    nicknameCancel: "Batal",
    nicknameEmailWarn: "Nama anda sekarang ialah bahagian depan e-mel anda. Sila tetapkan nama sebelum ia dipaparkan.",
    submit: "Hantar",
    submitEdit: "Kemas kini",
    loginTitle: "Log masuk dan tulisan anda dihantar seperti yang ditulis",
    loginGoogle: "Teruskan dengan Google",
    loginKakao: "Teruskan dengan Kakao",
    linkWarn: "Pautan tidak boleh dimasukkan",
    saved: "Dihantar. Terima kasih!",
    errors: {
    login: "Sila log masuk.",
    unavailable: "Cuba lagi sebentar nanti.",
    body_short: "Tulis sekurang-kurangnya dua aksara.",
    body_long: "Maksimum 600 aksara.",
    downside_long: "Bahagian yang kurang maksimum 200 aksara.",
    link: "Pautan tidak boleh dimasukkan.",
    rating: "Penilaian tidak sah.",
    rating_needs_body: "Tambah sepatah dua kata — penilaian tanpa tulisan tidak diterima.",
    rate: "Cuba lagi dalam beberapa minit.",
    nickname_confirm: "Sila tetapkan nama sebelum menghantar.",
    nickname_short: "Nama sekurang-kurangnya 2 aksara.",
    nickname_long: "Nama maksimum 20 aksara.",
    nickname_link: "Nama tidak boleh mengandungi alamat atau e-mel.",
    nickname_impersonation: "Nama yang kelihatan rasmi atau seperti pasukan tidak dibenarkan.",
    image_type: "Fail imej sahaja (jpg, png, webp).",
    image_size: "Sila muat naik imej bawah 5 MB.",
    already_requested: "Anda sudah meminta semakan semula.",
    not_found: "Tidak dijumpai. Sila muat semula halaman.",
    bad_input: "Cuba lagi sebentar nanti.",
    locale: "Cuba lagi sebentar nanti.",
  },
  },
  hi: {
    formTitle: "सॉल्वर इस्तेमाल करके कैसा लगा?",
    tabReview: "समीक्षा",
    ratingLabel: "रेटिंग (वैकल्पिक)",
    placeholderReview: "दो शब्द लिखिए — अच्छा भी, कमी भी, जैसा लगा वैसा",
    downsideToggle: "+ कमियाँ भी लिखें",
    downsidePlaceholder: "कमियाँ (वैकल्पिक)",
    postingAs: (name) => `${name} नाम से पोस्ट होगा`,
    change: "बदलें",
    nicknameSave: "नाम सेव करें",
    nicknameCancel: "रद्द करें",
    nicknameEmailWarn: "अभी आपका नाम आपके ईमेल का पहला हिस्सा है। सार्वजनिक होने से पहले कृपया नाम चुनें।",
    submit: "पोस्ट करें",
    submitEdit: "अपडेट करें",
    loginTitle: "लॉग इन करें — आपका लिखा हुआ वैसे ही पोस्ट हो जाएगा",
    loginGoogle: "Google से जारी रखें",
    loginKakao: "Kakao से जारी रखें",
    linkWarn: "लिंक नहीं डाले जा सकते",
    saved: "पोस्ट हो गया। धन्यवाद!",
    errors: {
    login: "कृपया लॉग इन करें।",
    unavailable: "थोड़ी देर बाद फिर कोशिश करें।",
    body_short: "कम से कम दो अक्षर लिखें।",
    body_long: "ज़्यादा से ज़्यादा 600 अक्षर।",
    downside_long: "कमियों के लिए ज़्यादा से ज़्यादा 200 अक्षर।",
    link: "लिंक नहीं डाले जा सकते।",
    rating: "रेटिंग सही नहीं है।",
    rating_needs_body: "दो शब्द लिखिए — बिना लिखे सिर्फ़ रेटिंग नहीं ली जाती।",
    rate: "कुछ मिनट बाद फिर कोशिश करें।",
    nickname_confirm: "पोस्ट करने से पहले नाम चुनें।",
    nickname_short: "नाम कम से कम 2 अक्षर का हो।",
    nickname_long: "नाम ज़्यादा से ज़्यादा 20 अक्षर का हो।",
    nickname_link: "नाम में पता या ईमेल नहीं हो सकता।",
    nickname_impersonation: "आधिकारिक या टीम जैसे दिखने वाले नाम की अनुमति नहीं है।",
    image_type: "सिर्फ़ इमेज फ़ाइलें (jpg, png, webp)।",
    image_size: "5 MB से छोटी इमेज अपलोड करें।",
    already_requested: "आप पहले ही दोबारा जाँच का अनुरोध कर चुके हैं।",
    not_found: "नहीं मिला। पेज रीफ़्रेश करें।",
    bad_input: "थोड़ी देर बाद फिर कोशिश करें।",
    locale: "थोड़ी देर बाद फिर कोशिश करें।",
  },
  },
  tr: {
    formTitle: "Solver'ı denedin, nasıldı?",
    tabReview: "Yorum",
    ratingLabel: "Puan (isteğe bağlı)",
    placeholderReview: "Birkaç kelime yaz — iyisiyle kötüsüyle, olduğu gibi",
    downsideToggle: "+ Daha iyi olabilecekleri de yaz",
    downsidePlaceholder: "Daha iyi olabilecekler (isteğe bağlı)",
    postingAs: (name) => `Paylaşan: ${name}`,
    change: "Değiştir",
    nicknameSave: "Adı kaydet",
    nicknameCancel: "İptal",
    nicknameEmailWarn: "Adın şu an e-postanın ilk kısmı. Herkese açık olmadan önce bir ad seç.",
    submit: "Paylaş",
    submitEdit: "Güncelle",
    loginTitle: "Giriş yap, yazdığın olduğu gibi paylaşılsın",
    loginGoogle: "Google ile devam et",
    loginKakao: "Kakao ile devam et",
    linkWarn: "Bağlantı eklenemez",
    saved: "Paylaşıldı. Teşekkürler!",
    errors: {
    login: "Giriş yapman gerekiyor.",
    unavailable: "Birazdan tekrar dene.",
    body_short: "En az birkaç karakter yaz.",
    body_long: "En fazla 600 karakter.",
    downside_long: "Daha iyi olabilecekler için en fazla 200 karakter.",
    link: "Bağlantı eklenemez.",
    rating: "Geçersiz puan.",
    rating_needs_body: "Birkaç kelime ekle — metinsiz puan kabul etmiyoruz.",
    rate: "Birkaç dakika sonra tekrar dene.",
    nickname_confirm: "Paylaşmadan önce bir ad seç.",
    nickname_short: "Ad en az 2 karakter olmalı.",
    nickname_long: "Ad en fazla 20 karakter olabilir.",
    nickname_link: "Ad, adres veya e-posta içeremez.",
    nickname_impersonation: "Resmî hesap veya ekip üyesi gibi görünen adlar kullanılamaz.",
    image_type: "Yalnızca görsel dosyaları (jpg, png, webp).",
    image_size: "En fazla 5 MB boyutunda bir görsel yükle.",
    already_requested: "Yeniden incelenmesini zaten istedin.",
    not_found: "Bulunamadı. Sayfayı yenile.",
    bad_input: "Birazdan tekrar dene.",
    locale: "Birazdan tekrar dene.",
  },
  },
  vi: {
    formTitle: "Bạn thấy solver thế nào?",
    tabReview: "Đánh giá",
    ratingLabel: "Điểm (không bắt buộc)",
    placeholderReview: "Viết vài dòng — cả điểm hay lẫn điểm dở, đúng như bạn thấy",
    downsideToggle: "+ Thêm điều có thể tốt hơn",
    downsidePlaceholder: "Điều có thể tốt hơn (không bắt buộc)",
    postingAs: (name) => `Đăng với tên ${name}`,
    change: "Đổi",
    nicknameSave: "Lưu tên",
    nicknameCancel: "Hủy",
    nicknameEmailWarn: "Tên của bạn hiện là phần đầu email. Hãy chọn một tên trước khi tên này hiển thị công khai.",
    submit: "Đăng",
    submitEdit: "Cập nhật",
    loginTitle: "Đăng nhập để bài viết được đăng đúng như bạn viết",
    loginGoogle: "Tiếp tục với Google",
    loginKakao: "Tiếp tục với Kakao",
    linkWarn: "Không thể chèn liên kết",
    saved: "Đã đăng. Cảm ơn bạn!",
    errors: {
    login: "Bạn cần đăng nhập.",
    unavailable: "Hãy thử lại sau giây lát.",
    body_short: "Hãy viết ít nhất vài ký tự.",
    body_long: "Tối đa 600 ký tự.",
    downside_long: "Mục “Điều có thể tốt hơn” tối đa 200 ký tự.",
    link: "Không thể chèn liên kết.",
    rating: "Điểm không hợp lệ.",
    rating_needs_body: "Hãy thêm vài chữ — chúng tôi không nhận điểm mà không có nội dung.",
    rate: "Hãy thử lại sau vài phút.",
    nickname_confirm: "Hãy chọn tên trước khi đăng.",
    nickname_short: "Tên cần ít nhất 2 ký tự.",
    nickname_long: "Tên tối đa 20 ký tự.",
    nickname_link: "Tên không được chứa địa chỉ hoặc email.",
    nickname_impersonation: "Không được dùng tên trông giống tài khoản chính thức hoặc nhân viên.",
    image_type: "Chỉ nhận tệp ảnh (jpg, png, webp).",
    image_size: "Hãy tải lên ảnh nhỏ hơn 5 MB.",
    already_requested: "Bạn đã yêu cầu xem xét lại rồi.",
    not_found: "Không tìm thấy. Hãy tải lại trang.",
    bad_input: "Hãy thử lại sau giây lát.",
    locale: "Hãy thử lại sau giây lát.",
  },
  },
  ru: {
    formTitle: "Как тебе солвер?",
    tabReview: "Отзыв",
    ratingLabel: "Оценка (необязательно)",
    placeholderReview: "Напиши пару слов — хорошее и плохое, как есть",
    downsideToggle: "+ Добавить, что можно улучшить",
    downsidePlaceholder: "Что можно улучшить (необязательно)",
    postingAs: (name) => `Автор: ${name}`,
    change: "Изменить",
    nicknameSave: "Сохранить имя",
    nicknameCancel: "Отмена",
    nicknameEmailWarn: "Сейчас твоё имя — это начало адреса электронной почты. Выбери имя, пока оно не стало публичным.",
    submit: "Опубликовать",
    submitEdit: "Обновить",
    loginTitle: "Войди — и текст опубликуется в том виде, в каком написан",
    loginGoogle: "Войти через Google",
    loginKakao: "Войти через Kakao",
    linkWarn: "Ссылки добавлять нельзя",
    saved: "Опубликовано. Спасибо!",
    errors: {
    login: "Войди в аккаунт.",
    unavailable: "Попробуй ещё раз чуть позже.",
    body_short: "Напиши хотя бы пару символов.",
    body_long: "Не больше 600 символов.",
    downside_long: "В поле «Что можно улучшить» — не больше 200 символов.",
    link: "Ссылки добавлять нельзя.",
    rating: "Недопустимая оценка.",
    rating_needs_body: "Добавь пару слов — оценки без текста мы не принимаем.",
    rate: "Попробуй ещё раз через несколько минут.",
    nickname_confirm: "Перед публикацией выбери имя.",
    nickname_short: "Имя — минимум 2 символа.",
    nickname_long: "Имя — не больше 20 символов.",
    nickname_link: "Имя не может содержать адреса сайтов или почты.",
    nickname_impersonation: "Нельзя брать имена, похожие на официальные или на имена сотрудников.",
    image_type: "Только изображения (jpg, png, webp).",
    image_size: "Загрузи изображение размером меньше 5 МБ.",
    already_requested: "Повторная проверка уже запрошена.",
    not_found: "Не найдено. Обнови страницу.",
    bad_input: "Попробуй ещё раз чуть позже.",
    locale: "Попробуй ещё раз чуть позже.",
  },
  },
};

// APP_ONLY_COPY
/** New app entry/navigation copy, translated independently from the English source. */
export type FeedbackAppLabels = {
  menu: string;
  resultPrompt: string;
  thirdSolvePrompt: string;
  close: string;
  viewReviews: string;
  nicknameLabel: string;
};

export const appLabels: LocaleDict<FeedbackAppLabels> = {
  ko: {
    menu: "후기 남기기",
    resultPrompt: "써 보니 어땠나요?",
    thirdSolvePrompt: "세 번째 계산을 마쳤네요. 짧은 한마디도 좋아요",
    close: "닫기",
    viewReviews: "후기 보러 가기",
    nicknameLabel: "공개할 이름",
  },
  en: {
    menu: "Leave a review",
    resultPrompt: "How was it for you?",
    thirdSolvePrompt: "You've finished your third solve. Leave a few words about your experience",
    close: "Close",
    viewReviews: "View reviews",
    nicknameLabel: "Public name",
  },
  ja: {
    menu: "レビューを書く",
    resultPrompt: "使ってみてどうでしたか？",
    thirdSolvePrompt: "3回目の計算が終わりました。ひと言だけでも大歓迎です",
    close: "閉じる",
    viewReviews: "レビューを見る",
    nicknameLabel: "公開する名前",
  },
  es: {
    menu: "Dejar una reseña",
    resultPrompt: "¿Qué te ha parecido?",
    thirdSolvePrompt: "Has terminado tu tercer cálculo. Cuéntanos en unas palabras cómo te ha ido",
    close: "Cerrar",
    viewReviews: "Ver reseñas",
    nicknameLabel: "Nombre público",
  },
  pt: {
    menu: "Deixar uma avaliação",
    resultPrompt: "O que você achou?",
    thirdSolvePrompt: "Você terminou seu terceiro cálculo. Conte em poucas palavras como foi a experiência",
    close: "Fechar",
    viewReviews: "Ver avaliações",
    nicknameLabel: "Nome público",
  },
  de: {
    menu: "Bewertung schreiben",
    resultPrompt: "Wie hat es dir gefallen?",
    thirdSolvePrompt: "Deine dritte Berechnung ist fertig. Schreib ein paar Worte über deine Erfahrung",
    close: "Schließen",
    viewReviews: "Bewertungen ansehen",
    nicknameLabel: "Öffentlicher Name",
  },
  zh: {
    menu: "写评价",
    resultPrompt: "用起来怎么样？",
    thirdSolvePrompt: "你已完成第三次计算。写几句使用感受吧",
    close: "关闭",
    viewReviews: "查看评价",
    nicknameLabel: "公开显示的名字",
  },
  "zh-hant": {
    menu: "寫評價",
    resultPrompt: "用起來覺得如何？",
    thirdSolvePrompt: "你已完成第三次計算。寫幾句使用心得吧",
    close: "關閉",
    viewReviews: "查看評價",
    nicknameLabel: "公開顯示的名字",
  },
  fr: {
    menu: "Donner ton avis",
    resultPrompt: "Qu'en as-tu pensé ?",
    thirdSolvePrompt: "Ton troisième calcul est terminé. Raconte ton expérience en quelques mots",
    close: "Fermer",
    viewReviews: "Voir les avis",
    nicknameLabel: "Nom public",
  },
  id: {
    menu: "Tulis ulasan",
    resultPrompt: "Bagaimana pengalaman Anda?",
    thirdSolvePrompt: "Perhitungan ketiga Anda selesai. Ceritakan pengalaman Anda dalam beberapa kata",
    close: "Tutup",
    viewReviews: "Lihat ulasan",
    nicknameLabel: "Nama yang ditampilkan",
  },
  ms: {
    menu: "Beri ulasan",
    resultPrompt: "Bagaimana pengalaman anda?",
    thirdSolvePrompt: "Pengiraan ketiga anda telah selesai. Kongsikan pengalaman anda dalam beberapa patah perkataan",
    close: "Tutup",
    viewReviews: "Lihat ulasan",
    nicknameLabel: "Nama untuk paparan umum",
  },
  hi: {
    menu: "समीक्षा लिखें",
    resultPrompt: "आपको कैसा लगा?",
    thirdSolvePrompt: "आपकी तीसरी गणना पूरी हो गई। अपना अनुभव दो शब्दों में लिखिए",
    close: "बंद करें",
    viewReviews: "समीक्षाएँ देखें",
    nicknameLabel: "सार्वजनिक नाम",
  },
  tr: {
    menu: "Yorum yaz",
    resultPrompt: "Senin için nasıldı?",
    thirdSolvePrompt: "Üçüncü hesaplamanı bitirdin. Deneyimini birkaç kelimeyle anlat",
    close: "Kapat",
    viewReviews: "Yorumları gör",
    nicknameLabel: "Herkese açık ad",
  },
  vi: {
    menu: "Viết đánh giá",
    resultPrompt: "Bạn thấy thế nào?",
    thirdSolvePrompt: "Bạn vừa xong lần giải thứ ba. Hãy chia sẻ vài dòng cảm nhận",
    close: "Đóng",
    viewReviews: "Xem đánh giá",
    nicknameLabel: "Tên công khai",
  },
  ru: {
    menu: "Оставить отзыв",
    resultPrompt: "Как тебе?",
    thirdSolvePrompt: "Третий расчёт готов. Напиши пару слов о впечатлениях",
    close: "Закрыть",
    viewReviews: "Смотреть отзывы",
    nicknameLabel: "Публичное имя",
  },
};
